'use strict';var e=true,i=null,m=false;function q(){return function(){}}function v(c){return function(a){this[c]=a}}function y(c){return function(){return this[c]}}function z(c){return function(){return c}}var B={i:{},h:{}};
(function(){B.seal=function(a){return Object.seal?Object.seal(a):a};B.freeze=function(a){return Object.freeze?Object.freeze(a):a};B.Yh=function(a,b){this.x=a;this.y=b;B.seal(this)};var c=B.Yh.prototype;c.offset=function(a,b){this.x+=a;this.y+=b;return this};c.Kk=function(a,b){this.x*=a;this.y*=b;return this};B.Lc=function(a,b,d,o,f,g,j,k){if(Math.max(a,d)<Math.min(f,j)||Math.min(a,d)>Math.max(f,j)||Math.max(b,o)<Math.min(g,k)||Math.min(b,o)>Math.max(g,k))return m;var h=f-a+j-d,c=g-b+k-o,a=d-a,b=o-
b,f=j-f,g=k-g,k=Math.abs(b*f-g*a),a=a*c-b*h;return Math.abs(f*c-g*h)<=k&&Math.abs(a)<=k};B.rect=function(a,b,d,o){this.set(a,b,d,o);B.seal(this)};c=B.rect.prototype;c.set=function(a,b,d,o){this.left=a;this.top=b;this.right=d;this.bottom=o};c.width=function(){return this.right-this.left};c.height=function(){return this.bottom-this.top};c.offset=function(a,b){this.left+=a;this.top+=b;this.right+=a;this.bottom+=b;return this};c.th=function(a){return!(a.right<this.left||a.bottom<this.top||a.left>this.right||
a.top>this.bottom)};c.qa=function(a,b){return a>=this.left&&a<=this.right&&b>=this.top&&b<=this.bottom};B.Df=function(){this.Fa=this.Ea=this.Ha=this.Ga=this.Na=this.Ma=this.ka=this.ja=0;B.seal(this)};c=B.Df.prototype;c.de=function(a){this.ja=a.left;this.ka=a.top;this.Ma=a.right;this.Na=a.top;this.Ga=a.right;this.Ha=a.bottom;this.Ea=a.left;this.Fa=a.bottom};c.Jh=function(a,b){if(b===0)this.de(a);else{var d=Math.sin(b),o=Math.cos(b),f=a.left*d,g=a.top*d,j=a.right*d;d*=a.bottom;var k=a.left*o,h=a.top*
o,c=a.right*o;o*=a.bottom;this.ja=k-g;this.ka=h+f;this.Ma=c-g;this.Na=h+j;this.Ga=c-d;this.Ha=o+j;this.Ea=k-d;this.Fa=o+f}};c.offset=function(a,b){this.ja+=a;this.ka+=b;this.Ma+=a;this.Na+=b;this.Ga+=a;this.Ha+=b;this.Ea+=a;this.Fa+=b;return this};c.pg=function(a){a.left=Math.min(this.ja,this.Ma,this.Ga,this.Ea);a.top=Math.min(this.ka,this.Na,this.Ha,this.Fa);a.right=Math.max(this.ja,this.Ma,this.Ga,this.Ea);a.bottom=Math.max(this.ka,this.Na,this.Ha,this.Fa)};c.qa=function(a,b){var d=this.Ma-this.ja,
o=this.Na-this.ka,f=this.Ga-this.ja,g=this.Ha-this.ka,j=a-this.ja,k=b-this.ka,h=d*d+o*o,c=d*f+o*g,o=d*j+o*k,l=f*f+g*g,p=f*j+g*k,r=1/(h*l-c*c),d=(l*o-c*p)*r,h=(h*p-c*o)*r;if(d>=0&&h>0&&d+h<1)return e;d=this.Ea-this.ja;o=this.Fa-this.ka;h=d*d+o*o;c=d*f+o*g;o=d*j+o*k;r=1/(h*l-c*c);d=(l*o-c*p)*r;h=(h*p-c*o)*r;return d>=0&&h>0&&d+h<1};c.Qa=function(a,b){a%=4;a<0&&(a+=4);switch(a){case 0:return b?this.ja:this.ka;case 1:return b?this.Ma:this.Na;case 2:return b?this.Ga:this.Ha;case 3:return b?this.Ea:this.Fa;
default:return b?this.ja:this.ka}};c.wf=function(){return(this.ja+this.Ma+this.Ga+this.Ea)/4};c.xf=function(){return(this.ka+this.Na+this.Ha+this.Fa)/4};c.sh=function(a){var b=a.wf(),d=a.xf();if(this.qa(b,d))return e;b=this.wf();d=this.xf();if(a.qa(b,d))return e;var o,f,g,j,k,h,c,l;for(c=0;c<4;c++)for(l=0;l<4;l++)if(b=this.Qa(c,e),d=this.Qa(c,m),o=this.Qa(c+1,e),f=this.Qa(c+1,m),g=a.Qa(l,e),j=a.Qa(l,m),k=a.Qa(l+1,e),h=a.Qa(l+1,m),B.Lc(b,d,o,f,g,j,k,h))return e;return m};B.RGB=function(a,b,d){return Math.max(Math.min(a,
255),0)|Math.max(Math.min(b,255),0)<<8|Math.max(Math.min(d,255),0)<<16};B.Uk=function(a,b){for(var d in b)b.hasOwnProperty(d)&&(a[d]=b[d])};B.Hb=function(a,b){var d;b<1?a.shift():(d=a.slice(b+1),a.length=b,a.push.apply(a,d))};B.Ge=function(a,b){var d=jQuery.inArray(b,a);d>=0&&B.Hb(a,d)};B.Je=function(a,b,d){return a<b?b:a>d?d:a};B.J=function(a){return a/(180/Math.PI)};B.Cb=function(a){return a*(180/Math.PI)};B.Ke=function(a){a%=360;a<0&&(a+=360);return a};B.C=function(a){a%=2*Math.PI;a<0&&(a+=2*Math.PI);
return a};B.Lh=function(a){return B.Ke(B.Cb(a))};B.Wf=function(a){return B.C(B.J(a))};B.ic=function(a,b,d,o){return Math.atan2(o-b,d-a)};B.ad=function(a,b){if(a===b)return 0;var d=Math.sin(a),o=Math.cos(a),f=Math.sin(b),g=Math.cos(b),d=d*f+o*g;return d>=1?0:d<=-1?Math.PI:Math.acos(d)};B.Fe=function(a,b,d){var o=Math.sin(a),f=Math.cos(a),g=Math.sin(b),j=Math.cos(b);return Math.acos(o*g+f*j)>d?f*g-o*j>0?B.C(a+d):B.C(a-d):B.C(b)};B.Gb=function(a,b){var d=Math.sin(a),o=Math.cos(a),f=Math.sin(b),g=Math.cos(b);
return o*f-d*g<=0};B.Ob=function(a,b,d,o){a=d-a;b=o-b;return Math.sqrt(a*a+b*b)};B.te=function(a,b){return!a!==!b};B.uf=function(a,b,d){return a+(b-a)*d};B.Db=function(){this.jb={};this.Vb=0;this.Vc=[];this.Jb=e;B.seal(this)};c=B.Db.prototype;c.contains=function(a){return this.jb.hasOwnProperty(a.toString())};c.add=function(a){if(!this.contains(a))this.jb[a.toString()]=a,this.Vb++,this.Jb=m;return this};c.remove=function(a){if(this.contains(a))delete this.jb[a.toString()],this.Vb--,this.Jb=m;return this};
c.clear=function(){this.jb={};this.Vb=0;this.Vc.length=0;this.Jb=e;return this};c.uh=function(){return this.Vb===0};c.sk=y("Vb");c.ec=function(){if(!this.Jb){this.Vc.length=0;for(var a in this.jb)this.jb.hasOwnProperty(a)&&this.Vc.push(this.jb[a]);this.Jb=e}return this.Vc.slice(0)};B.ye=function(){this.V=this.Oc=this.y=this.gd=0;B.seal(this)};c=B.ye.prototype;c.add=function(a){this.y=a-this.gd;this.Oc=this.V+this.y;this.gd=this.Oc-this.V-this.y;this.V=this.Oc};c.reset=function(){this.V=this.Oc=this.y=
this.gd=0};B.Ef=function(a){return a.replace(/[-[\]{}()*+?.,\\^$|#\s]/g,"\\$&")};B.Wc=function(a){this.q=[];this.Lf(a);B.seal(this)};c=B.Wc.prototype;c.Lf=function(a){this.Wd=a;this.Yb=a.length/2;this.q.length=a.length;this.lc=this.Kb=-1;this.He=0};c.Gd=function(){return!this.Wd.length};c.Kf=function(a,b,d,o,f){this.q.length=8;this.Yb=4;this.q[0]=a.ja-b;this.q[1]=a.ka-d;this.q[2]=a.Ma-b;this.q[3]=a.Na-d;this.q[4]=a.Ga-b;this.q[5]=a.Ha-d;this.q[6]=a.Ea-b;this.q[7]=a.Fa-d;this.Kb=o;this.lc=f};c.ld=
function(a,b,d){if(!(this.Kb===a&&this.lc===b&&this.He===d)){this.Kb=a;this.lc=b;this.He=d;var o,f,g,j=0,c=1;d!==0&&(j=Math.sin(d),c=Math.cos(d));for(d=0,o=this.Yb;d<o;d++)f=this.Wd[d*2]*a,g=this.Wd[d*2+1]*b,this.q[d*2]=f*c-g*j,this.q[d*2+1]=g*c+f*j}};c.qa=function(a,b){if(a===this.q[0]&&b===this.q[1])return e;var d=-this.Kb*5-1,o=-this.lc*5-1,f=this.Kb*5+1,g,j,c,h,n,l,p=0,r=0;for(n=0,l=this.Yb;n<l;n++)g=this.q[n*2],j=this.q[n*2+1],c=this.q[(n+1)%l*2],h=this.q[(n+1)%l*2+1],B.Lc(d,o,a,b,g,j,c,h)&&
p++,B.Lc(f,-1,a,b,g,j,c,h)&&r++;return p%2===1||r%2===1};c.rh=function(a,b,d){if(this.qa(a.q[0]+b,a.q[1]+d))return e;if(a.qa(this.q[0]-b,this.q[1]-d))return e;var o,f,g,j,c,h,n,l,p,r,s,t;for(o=0,f=this.Yb;o<f;o++){c=this.q[o*2];h=this.q[o*2+1];n=this.q[(o+1)%f*2];l=this.q[(o+1)%f*2+1];for(g=0,j=a.Yb;g<j;g++)if(p=a.q[g*2]+b,r=a.q[g*2+1]+d,s=a.q[(g+1)%j*2]+b,t=a.q[(g+1)%j*2+1]+d,B.Lc(c,h,n,l,p,r,s,t))return e}return m}})();
(function(){B.vg=function(b){return new B.a(document.getElementById(b))};B.a=function(b){if(b&&b.getContext){this.canvas=b;this.ua=b.getContext("2d");b.c2runtime=this;this.width=b.width;this.height=b.height;this.z=e;if(!Date.now)Date.now=function(){return+new Date};this.plugins=[];this.types={};this.G=[];this.h=[];this.Kd={};this.tf=[];this.vd={};this.Ja=[];this.gc=[];this.Tc=[];this.oc=new B.Db;this.Zh=this.tb=this.sb=0;this.Rc=1;this.aa=new B.ye;this.Id=0;this.vf=e;this.Dc=this.yd=this.Qb=this.Qc=
this.Hd=this.xd=0;this.mc=i;this.qd=[];this.ud=[];this.rc=-1;this.Xd(i);this.yb=[];this.Ac=-1;this.Cc=0;this.Jd=e;this.Md=new B.Db;this.Hc=[];this.Pc=new B.Wc([]);this.Zc={};this.sf=this.zc=this.A=i;this.wd="";this.Sa=new Image;this.Sa.src="logo.png";this.load();this.go();this.D={};B.seal(this)}};var c=B.a.prototype;c.setSize=function(b,d){this.width=b;this.height=d;this.z=e};c.load=function(){if(this.ua){var b=B.ff();this.name=b[0];this.We=b[1];this.lb=new B.bc(this);var d,a,f,g,j,c,h,n,l,p;for(d=
0,a=b[2].length;d<a;d++)h=b[2][d],B.mg(h),l=new h[0](this),l.Pf=h[1],l.xh=h[2],l.t&&l.t(),B.seal(l),this.plugins.push(l);b=B.ff();for(d=0,a=b[3].length;d<a;d++){h=b[3][d];p=h[1];l=i;for(f=0,g=this.plugins.length;f<g;f++)if(this.plugins[f]instanceof p){l=this.plugins[f];break}p=new l.L(l);p.name=h[0];if(h[2])p.Sf=h[2][0],p.Tf=h[2][1];if(h[3])p.na=h[3];p.index=d;p.b=[];p.nc=[];p.Xa=[new B.selection(p)];p.Ia=0;p.Nb=i;p.ke=e;p.Vh=B.Uh;p.af=B.Ph;p.ah=B.Qh;p.w=B.Oh;p.Zb=B.Sh;p.Va=B.Th;p.xa=B.Rh;p.zd=B.Mh;
p.Ad=B.Nh;p.h=[];for(f=0,g=h[4].length;f<g;f++){n=h[4][f];var r=n[1],s=i;for(j=0,c=this.h.length;j<c;j++)if(this.h[j]instanceof r){s=this.h[j];break}if(!s)s=new r(this),s.Xb=new B.Db,s.t&&s.t(),B.seal(s),this.h.push(s);j=new s.L(s,p);j.name=n[0];j.t();B.seal(j);p.h.push(j)}p.global=h[5];p.t();B.seal(p);p.name&&(this.types[p.name]=p);this.G.push(p);if(l.Pf)f=new l.B(p),f.Uc=this.Cc,this.Cc++,f.Dd=0,f.gf=B.nf,f.toString=B.of,f.I=h[6],f.t(),B.seal(f),p.b.push(f)}for(d=0,a=b[4].length;d<a;d++)h=b[4][d],
h=new B.wa(this,h),B.seal(h),this.Kd[h.name]=h,this.tf.push(h);for(d=0,a=b[5].length;d<a;d++)h=b[5][d],h=new B.Ue(this,h),B.seal(h),this.vd[h.name]=h,this.Ja.push(h);for(d=0,a=this.Ja.length;d<a;d++)this.Ja[d].F();for(d=0,a=this.Tc.length;d<a;d++)this.Tc[d].F();delete this.Tc;this.wd=b[6];this.Td=b[7];this.Nk=b[8];this.Mk=b[9];this.Nc=Date.now()}};c.ng=function(){var b=0,d=0,a=e,f,g;for(f=0,g=this.gc.length;f<g;f++){var j=this.gc[f].Me;if(!j||j<=0)j=5E4;b+=j;this.gc[f].complete?d+=j:a=m}this.Gc=b==
0?0:d/b;return a};c.go=function(){if(this.ua)if(this.Gc=0,this.pf=-1,this.ng())this.lh();else{if(Date.now()-this.Nc>=500&&this.Sa.complete&&this.pf!=this.Gc){this.ua.clearRect(0,0,this.width,this.height);var b=this.width/2,d=this.height/2,a=this.Sa.width/2,f=this.Sa.height/2;this.ua.drawImage(this.Sa,Math.floor(b-a),Math.floor(d-f));d+=f+12;b-=a;b=Math.floor(b)+0.5;d=Math.floor(d)+0.5;this.ua.fillStyle="blue";this.ua.fillRect(b,d,Math.floor(this.Sa.width*this.Gc),6);this.ua.strokeStyle="black";this.ua.strokeRect(b,
d,this.Sa.width,6);this.ua.strokeStyle="white";this.ua.strokeRect(b-1,d-1,this.Sa.width+2,8);this.pf=this.Gc}setTimeout(function(d){return function(){d.go()}}(this),100)}};c.lh=function(){this.We?this.Kd[this.We].le():this.tf[0].le();this.Hd=this.Nc=Date.now();this.za()};c.za=function(){this.zh();if(this.z)this.Ra(),this.z=m;this.Qc++;this.Qb++;this.yd++;var b=window.requestAnimationFrame||window.mozRequestAnimationFrame||window.webkitRequestAnimationFrame||window.msRequestAnimationFrame||window.oRequestAnimationFrame;
b?b(function(d){return function(){d.za()}}(this),this.canvas):setTimeout(function(d){return function(){d.za()}}(this),16)};c.zh=function(){var b,d,a,f,g,j,c;b=Date.now();if(b-this.Hd>=1E3)this.Hd+=1E3,this.xd=this.yd,this.yd=0;if(this.vf){if(this.Id!==0)if(d=b-this.Id,d===0){this.Zh++;if(this.dl>=10)this.vf=m;this.tb=1/60}else if(this.tb=d/1E3,this.tb>0.1)this.tb=0.1;this.Id=b}this.sb=this.tb*this.Rc;this.aa.add(this.sb);this.we();this.lb.Gh();if(this.mc){this.A.Kh();this.mc.le();for(b=0,d=this.G.length;b<
d;b++)if(c=this.G[b],c.global||c.kb.Pf)for(a=0,f=c.b.length;a<f;a++){var h=c.b[a];h.Bh&&h.Bh()}this.mc=i;this.Jd=this.z=e}for(b=0,d=this.G.length;b<d;b++){c=this.G[b];for(a=0,f=c.b.length;a<f;a++)if(h=c.b[a],h.oa)for(g=0,j=h.oa.length;g<j;g++)h.oa[g].za()}a=this.Md.ec();for(b=0,d=a.length;b<d;b++)a[b].za();for(b=0,d=this.Ja.length;b<d;b++)this.Ja[b].Bd=m;this.A.qc&&this.A.qc.Q();this.Hc.length=0;this.Jd=m};c.cc=function(b){this.Md.add(b)};c.Ze=function(b){return!b||b.Bc===-1?this.sb:this.tb*b.Bc};
c.Ra=function(){this.A.Ra(this.ua)};c.De=function(b){b&&this.qd.push(b)};c.xe=function(b){this.oc.add(b)};c.we=function(){var b,d,a,f,g,j,c,h=this.oc.ec();for(f=0,j=h.length;f<j;f++){b=h[f];d=b.type;a=d.b;for(g=0,c=this.qd.length;g<c;g++)this.qd[g](b);B.Ge(a,b);if(b.m)B.Hb(b.m.b,b.Ub()),b.m.$a=e;if(b.oa)for(g=0,c=b.oa.length;g<c;g++)a=b.oa[g],a.Fc&&a.Fc(),a.l.Xb.remove(b);this.Md.remove(b);for(g=0,c=this.lb.Ca.length;g<c;g++)a=this.lb.Ca[g],a.Bb.hasOwnProperty(d.index)&&B.Ge(a.Bb[d.index],b);b.Fc&&
b.Fc();this.Dc--;d.nc.length<32&&d.nc.push(b)}if(!this.oc.uh())this.z=e;this.oc.clear()};c.Ne=function(b,d,a,f){return this.pd(b.Nb,d,a,f)};c.pd=function(b,d,a,f){var g,j,c,h=this.G[b[1]],n=h.kb.xh,l,p=m;h.nc.length?(l=h.nc.pop(),p=e,h.kb.B.call(l,h)):l=new h.kb.B(h);l.Uc=this.Cc;this.Cc++;l.Dd=0;l.gf=B.nf;h.ke=e;var r=b[2];if(p){for(g=0,j=r.length;g<j;g++)l.P[g]=r[g];for(c in l.D)l.D.hasOwnProperty(c)&&delete l.D[c]}else l.P=r.slice(0),l.D={};if(n)g=b[0],l.x=typeof a==="undefined"?g[0]:a,l.y=typeof f===
"undefined"?g[1]:f,l.cl=g[2],l.width=g[3],l.height=g[4],l.depth=g[5],l.e=g[6],l.opacity=g[7],l.Ka=g[8],l.$=g[9],p?(l.X.set(0,0,0,0),l.Aa.de(l.X),l.kc.length=0):(l.X=new B.rect(0,0,0,0),l.Aa=new B.Df,l.kc=[],l.n=B.n,l.$c=B.$c,l.qa=B.ph,l.Ba=B.Ba,l.Ub=B.qh),l.ed=e,l.la=e,l.Bc=-1,l.m=d,l.ue=d.b.length,this.z=e;l.toString=B.of;if(p)for(g=0,j=h.h.length;g<j;g++){r=h.h[g];n=l.oa[g];r.l.B.call(n,r,l);c=b[3][g];for(a=0,f=c.length;a<f;a++)n.I[a]=c[a];n.t();r.l.Xb.add(l)}else{l.oa=[];for(g=0,j=h.h.length;g<
j;g++)r=h.h[g],n=new r.l.B(r,l),n.I=b[3][g].slice(0),n.t(),B.seal(n),l.oa.push(n),r.l.Xb.add(l)}c=b[4];if(p)for(g=0,j=c.length;g<j;g++)l.I[g]=c[g];else l.I=c.slice(0);h.b.push(l);d&&d.b.push(l);this.Dc++;l.t();p||B.seal(l);return l};c.cf=function(b){var d,a;for(d=0,a=this.A.H.length;d<a;d++){var f=this.A.H[d];if(f.name===b)return f}return i};c.df=function(b){b=Math.floor(b);b<0&&(b=0);b>=this.A.H.length&&(b=this.A.H.length-1);return this.A.H[b]};c.bf=function(b){return typeof b==="number"?this.df(b):
this.cf(b.toString())};B.wa=function(b,d){this.a=b;this.qc=i;this.scrollX=this.a.width/2;this.scrollY=this.a.height/2;this.name=d[0];this.width=d[1];this.height=d[2];this.Zf=d[3];this.Of=d[4];var a=d[5],f,g;this.H=[];for(f=0,g=a.length;f<g;f++){var j=new B.m(this,a[f]);j.zf=f;B.seal(j);this.H.push(j)}a=d[6];this.vb=[];for(f=0,g=a.length;f<g;f++){var j=a[f],c=this.a.G[j[1]];if(!c.Nb)c.Nb=j;this.vb.push(j)}};var a=B.wa.prototype;a.le=function(){if(this.Of)this.qc=this.a.vd[this.Of];this.a.A=this;this.scrollX=
this.a.width/2;this.scrollY=this.a.height/2;var b,d,a,f,g,c;for(b=0,a=this.a.G.length;b<a;b++){g=this.a.G[b].b;for(d=0,f=g.length;d<f;d++)if(c=g[d],c.m){var k=c.m.zf;k>=this.H.length&&(k=this.H.length-1);c.m=this.H[k];c.m.b.push(c);c.m.$a=e}}for(b=0,a=this.H.length;b<a;b++)this.H[b].ug();for(b=0,d=0,a=this.vb.length;b<a;b++)c=this.a.pd(this.vb[b],i),c.type.global||(this.vb[d]=this.vb[b],d++);this.vb.length=d;this.a.trigger(B.bc.prototype.o.Be,i)};a.Kh=function(){this.a.trigger(B.bc.prototype.o.gg,
i);this.a.lb.Ca.length=0;var b,d,a,f,g,c;for(b=0,d=this.H.length;b<d;b++){g=this.H[b].b;for(a=0,f=g.length;a<f;a++)c=g[a],c.type.global||this.a.xe(c);this.a.we();g.length=0;this.H[b].$a=e}};a.Ra=function(b){b.clearRect(0,0,this.a.width,this.a.height);var d,a;for(d=0,a=this.H.length;d<a;d++)this.H[d].la&&this.H[d].Ra(b)};a.ef=function(){var b=this.H[0].scale,d,a,f;for(d=1,a=this.H.length;d<a;d++)if(f=this.H[d],f.scale<b)b=f.scale;return b};a.Jc=function(b){if(!this.Zf){var d=this.a.width*(1/this.ef())/
2;b>this.width-d&&(b=this.width-d);b<d&&(b=d)}if(this.scrollX!==b)this.scrollX=b,this.a.z=e};a.Kc=function(b){if(!this.Zf){var d=this.a.height*(1/this.ef())/2;b>this.height-d&&(b=this.height-d);b<d&&(b=d)}if(this.scrollY!==b)this.scrollY=b,this.a.z=e};B.m=function(b,d){this.wa=b;this.a=b.a;this.b=[];this.scale=1;this.pe=this.se=this.re=this.qe=0;this.$a=m;this.name=d[0];this.index=d[1];this.la=d[2];this.og=d[3];this.Xf=d[4];this.Af=d[5];this.Bf=d[6];this.opacity=d[7];this.Xg=d[8];var a=d[9],f,g;this.ub=
[];for(f=0,g=a.length;f<g;f++){var c=a[f],k=this.a.G[c[1]];if(!k.Nb)k.Nb=c;this.ub.push(c)}};a=B.m.prototype;a.ug=function(){var b,d,a,f;for(b=0,d=0,a=this.ub.length;b<a;b++)f=this.a.pd(this.ub[b],this),f.type.global||(this.ub[d]=this.ub[b],d++);this.ub.length=d};a.Wh=function(){if(this.$a){var b,d;for(b=0,d=this.b.length;b<d;b++)this.b[b].ue=b;this.$a=m}};a.Ra=function(b){var d=this.Xg||this.opacity!=1,a=this.a.canvas,f=b;if(d){if(!this.a.zc)this.a.zc=document.createElement("canvas"),a=this.a.zc,
a.width=this.a.width,a.height=this.a.height,this.a.sf=a.getContext("2d");a=this.a.zc;f=this.a.sf;if(a.width!=this.a.width)a.width=this.a.width;if(a.height!=this.a.height)a.height=this.a.height;this.Xf&&f.clearRect(0,0,this.a.width,this.a.height)}if(!this.Xf)f.fillStyle=this.og,f.fillRect(0,0,this.a.width,this.a.height);f.save();var g=this.md(0),c=this.nd(0);this.a.Td&&(g=Math.round(g),c=Math.round(c));this.qe=g;this.se=c;this.re=g+this.a.width*(1/this.scale);this.pe=c+this.a.height*(1/this.scale);
f.scale(this.scale,this.scale);f.translate(-g,-c);var k,h;for(g=0,c=this.b.length;g<c;g++)if(k=this.b[g],k.la)k.Ba(),h=k.X,h.right<this.qe||h.bottom<this.se||h.left>this.re||h.top>this.pe||k.Ra(f);f.restore();if(d)b.globalAlpha=this.opacity,b.drawImage(a,0,0),b.globalAlpha=1};a.md=function(b){var d=this.a.width/2,d=(this.wa.scrollX-d)*this.Af+d,a=1/this.scale;d-=this.a.width*a/2;return d+b*a};a.nd=function(b){var d=this.a.height/2,d=(this.wa.scrollY-d)*this.Bf+d,a=1/this.scale;d-=this.a.height*a/
2;return d+b*a};a.vk=function(b){var d=this.a.width/2,d=(this.wa.scrollX-d)*this.Af+d,a=1/this.scale;d-=this.a.width*a/2;return b/a-d};a.wk=function(b){var d=this.a.height/2,d=(this.wa.scrollY-d)*this.Bf+d,a=1/this.scale;d-=this.a.height*a/2;return b/a-d};c.Wg=function(b){var d=b.width,a=b.height,f=document.createElement("canvas");f.width=d;f.height=a;var g=f.getContext("2d");g.drawImage(b,0,0);var b=g.getImageData(0,0,d,a),c=g.createImageData(d,a),k=d*4,h,n,l,p;for(n=0;n<a;n++)for(h=0;h<d;h++)l=
n*k+h*4,p=(a-1-n)*k+h*4,c.data[p+0]=b.data[l+0],c.data[p+1]=b.data[l+1],c.data[p+2]=b.data[l+2],c.data[p+3]=b.data[l+3];g.putImageData(c,0,0);d=new Image;d.src=f.toDataURL();return d}})();
(function(){B.Ue=function(d,b){this.a=d;this.dc={};this.Cd=this.Bd=m;this.kf=new B.Db;this.name=b[0];var a=b[1];this.eb=[];var g,c;for(g=0,c=a.length;g<c;g++)this.lf(a[g],i,this.eb)};var c=B.Ue.prototype;c.toString=y("name");c.lf=function(d,b,a){switch(d[0]){case 0:d=new B.Se(this,b,d);B.seal(d);d.wh()?this.oh(d):a.push(d);break;case 1:d=new B.sc(this,b,d);B.seal(d);a.push(d);break;case 2:d=new B.Te(this,b,d),B.seal(d),a.push(d)}};c.F=function(){var d,b;for(d=0,b=this.eb.length;d<b;d++)this.eb[d].F()};
c.Q=function(){this.Bd=e;var d,b;for(d=0,b=this.eb.length;d<b;d++){var a=this.eb[d];a.Q();this.a.od(a.u)}};B.selection=function(d){this.type=d;this.b=[];this.s=e};var a=B.selection.prototype;a.hf=function(){return this.s?this.type.b.length:this.b.length};a.Z=function(){return this.s?this.type.b:this.b};a.Pk=function(d){this.s?(this.s=m,this.b.length=1,this.b[0]=d):jQuery.inArray(d,this.b)===-1&&this.b.push(d)};a=B.a.prototype;a.od=function(d){var b,a;for(b=0,a=d.length;b<a;b++)d[b].w().s=e};a.Zb=
function(d){var b,a;for(b=0,a=d.length;b<a;b++)d[b].Zb()};a.Va=function(d){var b,a;for(b=0,a=d.length;b<a;b++)d[b].Va()};a.xa=function(d){var b,a;for(b=0,a=d.length;b<a;b++)d[b].xa()};B.Se=function(d,b,a){this.sheet=d;this.parent=b;this.a=d.a;this.u=[];this.je=m;this.W=[];this.Pa=[];this.ya=[];if(a[1])this.mh=a[1][1],a[1][0]&&(this.a.Zc[this.mh]=e);var g=a[2];for(d=0,b=g.length;d<b;d++){var c=new B.Le(this,g[d]);B.seal(c);this.W.push(c);this.Ee(c.type)}g=a[3];for(d=0,b=g.length;d<b;d++)c=new B.action(this,
g[d]),B.seal(c),this.Pa.push(c);if(a.length===5){a=a[4];for(d=0,b=a.length;d<b;d++)this.sheet.lf(a[d],this,this.ya)}};var b=B.Se.prototype;b.F=function(){var d,b;for(d=0,b=this.W.length;d<b;d++)this.W[d].F();for(d=0,b=this.Pa.length;d<b;d++)this.Pa[d].F();for(d=0,b=this.ya.length;d<b;d++)this.ya[d].F()};b.Ee=function(b){b&&jQuery.inArray(b,this.u)===-1&&this.u.push(b)};b.Mc=function(){this.je=e;this.parent&&this.parent.Mc()};b.wh=function(){return this.W.length?this.W[0].trigger:m};b.Q=function(){var b,
a=this.a.Y();a.fa=this;for(a.pa=0,b=this.W.length;a.pa<b;a.pa++)if(!this.W[a.pa].Q())return m;this.Hf()};b.Hf=function(){var b=this.a.Y(),a;for(b.ma=0,a=this.Pa.length;b.ma<a;b.ma++)if(this.Pa[b.ma].Q())return;this.If()};b.Fh=function(){var b=this.a.Y(),a;for(a=this.Pa.length;b.ma<a;b.ma++)if(this.Pa[b.ma].Q())return;this.If()};b.If=function(){if(this.ya.length){var b,a,f,g,c=this.ya.length-1;if(this.je)for(b=0,a=this.ya.length;b<a;b++)f=this.ya[b],(g=!this.uk&&b<c)&&this.a.Va(f.u),f.Q(),g?this.a.xa(f.u):
this.a.od(f.u);else for(b=0,a=this.ya.length;b<a;b++)this.ya[b].Q()}};b.Hh=function(){var b,a;for(b=0,a=this.W.length;b<a;b++)if(!this.W[b].Q())return m;return e};b.Wa=function(){this.a.Qb++;var b=this.a.Y().pa,a=this.a.Xd(this);for(a.pa=b+1,b=this.W.length;a.pa<b;a.pa++)if(!this.W[a.pa].Q()){this.a.Ud();return}this.Hf();this.a.Ud()};B.Le=function(b,a){this.ta=b;this.sheet=b.sheet;this.a=b.a;this.p=[];this.k=[];this.D={};this.U=a[1];this.trigger=a[3];this.Fk=a[4];this.wc=a[5];this.yh=a[6];a[0]===
-1?(this.type=i,this.Q=this.be):(this.type=this.a.G[a[0]],this.Q=this.yh?this.Ih:this.ae,a[2]?(this.fd=this.type.zd(a[2]),this.da=this.type.Ad(a[2])):(this.fd=i,this.da=-1),this.ta.parent&&this.ta.parent.Mc());if(a.length===8){var f,g,c=a[7];for(f=0,g=c.length;f<g;f++){var k=new B.Pd(this,c[f]);B.seal(k);this.p.push(k)}this.k.length=c.length}};b=B.Le.prototype;b.F=function(){var b,a;for(b=0,a=this.p.length;b<a;b++)this.p[b].F()};b.be=function(){var b,a;for(b=0,a=this.p.length;b<a;b++)this.k[b]=this.p[b].get();
return B.te(this.U.apply(this.a.lb,this.k),this.wc)};b.Ih=function(){var b,a;for(b=0,a=this.p.length;b<a;b++)this.k[b]=this.p[b].get();return this.U.apply(this.type,this.k)};b.ae=function(){var b,a,f,g,c,k=this.type.w();if(k.s){k.b.length=0;for(b=0,f=this.type.b.length;b<f;b++){c=this.type.b[b];for(a=0,g=this.p.length;a<g;a++)this.k[a]=this.p[a].get(b);a=this.da>-1?this.U.apply(c.oa[this.da],this.k):this.U.apply(c,this.k);B.te(a,this.wc)&&k.b.push(c)}k.s=m}else{var h=0;for(b=0,f=k.b.length;b<f;b++){c=
k.b[b];for(a=0,g=this.p.length;a<g;a++)this.k[a]=this.p[a].get(b);a=this.da>-1?this.U.apply(c.oa[this.da],this.k):this.U.apply(c,this.k);B.te(a,this.wc)&&(k.b[h]=c,h++)}k.b.length=h}return k.hf()};B.action=function(b,a){this.ta=b;this.sheet=b.sheet;this.a=b.a;this.p=[];this.k=[];this.D={};this.U=a[1];a[0]===-1?(this.type=i,this.Q=this.be):(this.type=this.a.G[a[0]],this.Q=this.ae,a[2]?(this.fd=this.type.zd(a[2]),this.da=this.type.Ad(a[2])):(this.fd=i,this.da=-1));if(a.length===4){var f,g,c=a[3];for(f=
0,g=c.length;f<g;f++){var k=new B.Pd(this,c[f]);B.seal(k);this.p.push(k)}this.k.length=c.length}};b=B.action.prototype;b.F=function(){var b,a;for(b=0,a=this.p.length;b<a;b++)this.p[b].F()};b.be=function(){var b,a;for(b=0,a=this.p.length;b<a;b++)this.k[b]=this.p[b].get();return this.U.apply(this.a.lb,this.k)};b.ae=function(){var b=this.type.w().Z(),a,f,g,c;for(a=0,g=b.length;a<g;a++){for(f=0,c=this.p.length;f<c;f++)this.k[f]=this.p[f].get(a);this.da>-1?this.U.apply(b[a].oa[this.da],this.k):this.U.apply(b[a],
this.k)}return m};B.Pd=function(b,a){this.Ab=b;this.ta=b.ta;this.sheet=b.sheet;this.a=b.a;this.type=a[0];switch(a[0]){case 0:case 1:case 7:this.Rb=new B.ga(this,a[1]);this.ac=0;this.get=this.fh;this.d=new B.tc;break;case 5:this.Rb=new B.ga(this,a[1]);this.ac=0;this.get=this.ih;this.d=new B.tc;break;case 3:case 8:this.tg=a[1];this.get=this.dh;break;case 6:this.wa=this.a.Kd[a[1]];this.get=this.jh;break;case 9:this.key=a[1];this.get=this.hh;break;case 4:this.object=this.a.G[a[1]];this.get=this.kh;this.ta.Ee(this.object);
this.Ab instanceof B.action?this.ta.Mc():this.ta.parent&&this.ta.parent.Mc();break;case 10:this.index=a[1];this.get=this.gh;break;case 11:this.oe=a[1];this.fb=i;this.get=this.eh;break;case 2:this.file=a[1],this.get=this.bh}};b=B.Pd.prototype;b.F=function(){if(this.type===11)this.fb=this.a.$e(this.oe,this.ta.parent);this.Rb&&this.Rb.F()};b.fh=function(b){this.ac=b||0;this.Rb.get(this.d);return this.d.data};b.kh=y("object");b.dh=y("tg");b.ih=function(b){this.ac=b||0;this.Rb.get(this.d);return this.d.O()?
this.a.df(this.d.data):this.a.cf(this.d.data)};b.jh=y("wa");b.hh=y("key");b.gh=y("index");b.eh=y("fb");b.bh=y("file");B.sc=function(b,a,f){this.sheet=b;this.parent=a;this.a=b.a;this.u=[];this.name=f[1];this.fc=f[2];this.data=this.mf=f[3]};b=B.sc.prototype;b.F=q();b.Q=function(){if(this.parent)this.data=this.mf};B.Te=function(b,a,f){this.sheet=b;this.parent=a;this.a=b.a;this.u=[];this.vc=i;this.nh=f[1]};b=B.Te.prototype;b.F=function(){this.vc=this.a.vd[this.nh];this.sheet.kf.add(this.vc)};b.Q=function(){this.parent&&
this.a.Zb(this.a.G);this.vc.Bd||this.vc.Q();this.parent&&this.a.xa(this.a.G)};a.Wk=function(b,a,f,g){var c=b.w(),k,h,n,l,p;if(c.s){if(!g)c.s=m,c.b.length=0;for(k=0,n=b.b.length;k<n;k++)if(h=b.b[k],h.Ba(),l=h.m.md(a),p=h.m.nd(f),h.qa(l,p))if(g)return m;else c.b.push(h)}else{b=0;for(k=0,n=c.b.length;k<n;k++)if(h=c.b[k],h.Ba(),l=h.m.md(a),p=h.m.nd(f),h.qa(l,p))if(g)return m;else c.b[b]=c.b[k],b++;if(!g)c.b.length=b}return g?e:c.hf()};a.wb=function(b){var a=B.C(b.e);return b.dd&&a>Math.PI/2&&a<=Math.PI*
3/2||b.cd&&a>=Math.PI};a.Ya=function(b,a){if(!b||!a)return m;if(b===a)return m;b.Ba();a.Ba();if(!b.X.th(a.X))return m;if(!b.Aa.sh(a.Aa))return m;var f=b.ea&&!b.ea.Gd(),g=a.ea&&!a.ea.Gd();if(!f&&!g)return e;f?(b.ea.ld(b.width,b.height*(this.wb(b)?-1:1),b.e),f=b.ea):(this.Pc.Kf(b.Aa,b.x,b.y,b.width,b.height),f=this.Pc);g?(a.ea.ld(a.width,a.height*(this.wb(a)?-1:1),a.e),g=a.ea):(this.Pc.Kf(a.Aa,a.x,a.y,a.width,a.height),g=this.Pc);return f.rh(g,a.x-b.x,a.y-b.y)};a.Za=function(b){var a=i,f,g;if(!B.h.ia)return i;
for(f=0,g=this.h.length;f<g;f++)if(this.h[f]instanceof B.h.ia){a=this.h[f];break}if(!a)return i;var c=a.Xb.ec();for(f=0,g=c.length;f<g;++f)if(a=c[f],this.Ya(b,a))return a;return i};a.Dh=function(b,a,f,g){var g=g||50,c=b.x,k=b.y,h,n=i;for(h=0;h<g;h++)if(b.x=Math.floor(c+a*h),b.y=Math.floor(k+f*h),b.n(),!this.Ya(b,n)&&(n=this.Za(b),!n))return e;b.x=c;b.y=k;b.n();return m};a.Zd=function(b,a){for(var f=typeof a==="undefined"?100:a,g=0,c=b.x,k=b.y,h=0,n=0,l=0,p=i;g<=f;){switch(h){case 0:n=0;l=-1;g++;break;
case 1:n=1;l=-1;break;case 2:n=1;l=0;break;case 3:l=n=1;break;case 4:n=0;l=1;break;case 5:n=-1;l=1;break;case 6:n=-1;l=0;break;case 7:l=n=-1}h=(h+1)%8;b.x=Math.floor(c+n*g);b.y=Math.floor(k+l*g);b.n();if(!this.Ya(b,p)&&(p=this.Za(b),!p))return e}b.x=c;b.y=k;b.n();return m};a.Ff=function(b,a){this.Hc.push([b,a])};a.sg=function(b,a){var f,g,c;for(f=0,g=this.Hc.length;f<g;f++)if(c=this.Hc[f],c[0]==b&&c[1]==a||c[0]==a&&c[1]==b)return e;return m};a.rg=function(b,a,f){var c=b.x,j=b.y,k=B.Ob(a,f,c,j),h=
B.ic(a,f,c,j),n=this.Za(b);if(!n)return B.C(h+Math.PI);var l=n,p,r,s,t,w=B.J(5);for(p=1;p<36;p++)if(r=h-p*w,b.x=a+Math.cos(r)*k,b.y=f+Math.sin(r)*k,b.n(),!this.Ya(b,l)&&(l=this.Za(b),!l)){s=r;break}p===36&&(s=B.C(h+Math.PI));l=n;for(p=1;p<36;p++)if(r=h+p*w,b.x=a+Math.cos(r)*k,b.y=f+Math.sin(r)*k,b.n(),!this.Ya(b,l)&&(l=this.Za(b),!l)){t=r;break}p===36&&(t=B.C(h+Math.PI));b.x=c;b.y=j;b.n();if(t===s)return t;b=B.ad(t,s)/2;b=B.Gb(t,s)?B.C(s+b+Math.PI):B.C(t+b);s=Math.cos(h);h=Math.sin(h);t=Math.cos(b);
b=Math.sin(b);a=s*t+h*b;return B.ic(0,0,s-2*a*t,h-2*a*b)};c.oh=function(b){this.a.Tc.push(b);var a;a=b.W[0].type?b.W[0].type.name:"system";this.dc[a]||(this.dc[a]=[]);a=this.dc[a];var f=b.W[0].U,c,j;for(c=0,j=a.length;c<j;c++)if(a[c].method==f){a[c].Ve.push(b);return}a.push({method:f,Ve:[b]})};a.trigger=function(b,a){if(!this.A)return m;var f=this.A.qc;if(!f)return m;var c,j;for(c=0,j=this.Ja.length;c<j;c++)this.Ja[c].Cd=m;return this.Yf(b,a,f)};a.Yf=function(b,a,f){if(f.Cd)return m;f.Cd=e;var c=
f.kf.ec(),j=m,k,h,n,l;for(k=0,n=c.length;k<n;k++)var p=this.Yf(b,a,c[k]),j=j||p;k=a?a.type.name:"system";if(!f.dc[k])return j;c=f.dc[k];f=i;for(k=0,n=c.length;k<n;k++)if(c[k].method==b){f=c[k].Ve;break}if(!f)return j;for(k=0,n=f.length;k<n;k++){b=f[k];this.Zb(b.u);this.Xd(b);if(a)c=a.type.w(),c.s=m,c.b.length=1,c.b[0]=a;c=e;if(b.parent){p=this.Y().Rf;for(h=b.parent;h;)p.push(h),h=h.parent;p.reverse();for(h=0,l=p.length;h<l;h++)this.Zb(p[h].u);for(h=0,l=p.length;h<l;h++)if(!p[h].Hh()){c=m;break}for(h=
0,l=p.length;h<l;h++)this.xa(p[h].u)}c&&(this.Qb++,b.Q(),j=e);this.xa(b.u);this.Ud()}return j};B.Re=function(){this.Rf=[];this.reset(i);B.seal(this)};c=B.Re.prototype;c.reset=function(b){this.fa=b;this.ma=this.pa=0;this.Rf.length=0};c.Fd=function(){return this.fa.je?e:this.pa<this.fa.W.length-1?!!this.fa.u.length:m};a.Tb=function(){var b=this.Y();return b.fa.W[b.pa]};a.Zg=function(){var b=this.Y();return b.fa.Pa[b.ma]};a.Xd=function(b){this.rc++;this.rc>=this.ud.length&&this.ud.push(new B.Re);var a=
this.Y();a.reset(b);return a};a.Ud=function(){this.rc--};a.Y=function(){return this.ud[this.rc]};a.Yd=function(b){this.Ac++;this.Ac>=this.yb.length&&this.yb.push(B.seal({name:b,index:0}));var a=this.Ye();a.name=b;a.index=0;return a};a.Vd=function(){this.Ac--};a.Ye=function(){return this.yb[this.Ac]};a.$e=function(b,a){for(var f,c,j,k,h,n;a;){for(f=0,c=a.ya.length;f<c;f++)if(n=a.ya[f],n instanceof B.sc&&b.toLowerCase()===n.name.toLowerCase())return n;a=a.parent}for(f=0,c=this.Ja.length;f<c;f++){h=
this.Ja[f];for(j=0,k=h.eb.length;j<k;j++)if(n=h.eb[j],n instanceof B.sc&&b.toLowerCase()===n.name.toLowerCase())return n}return i}})();
(function(){B.ga=function(a,b){this.Ab=a;this.a=a.a;this.type=b[0];this.get=[this.Kg,this.Gg,this.Sg,this.Vg,this.Ag,this.Tg,this.Og,this.Dg,this.Ng,this.Rg,this.Bg,this.Qg,this.Eg,this.Pg,this.Lg,this.Mg,this.Hg,this.Ig,this.Cg,this.Ug,this.Qe,this.Jg,this.Qe,this.Fg][this.type];var d=i;this.d=new B.tc;switch(this.type){case 0:case 1:case 2:this.value=b[1];break;case 3:this.first=new B.ga(a,b[1]);break;case 18:this.first=new B.ga(a,b[1]);this.R=new B.ga(a,b[2]);this.me=new B.ga(a,b[3]);break;case 19:this.U=
b[1];this.k=[];this.p=[];b.length===3?(d=b[2],this.k.length=d.length+1):this.k.length=1;break;case 20:this.Ua=this.a.G[b[1]];this.da=-1;this.U=b[2];this.Ta=b[3]?new B.ga(a,b[3]):i;this.k=[];this.p=[];b.length===5?(d=b[4],this.k.length=d.length+1):this.k.length=1;break;case 21:this.Ua=this.a.G[b[1]];this.Ta=b[2]?new B.ga(a,b[2]):i;this.$f=b[3];break;case 22:this.Ua=this.a.G[b[1]];this.rk=this.Ua.zd(b[2]);this.da=this.Ua.Ad(b[2]);this.U=b[3];this.Ta=b[4]?new B.ga(a,b[4]):i;this.k=[];this.p=[];b.length===
6?(d=b[5],this.k.length=d.length+1):this.k.length=1;break;case 23:this.oe=b[1],this.fb=i}if(this.type>=4&&this.type<=17)this.first=new B.ga(a,b[1]),this.R=new B.ga(a,b[2]);if(d){var c,f;for(c=0,f=d.length;c<f;c++)this.p.push(new B.ga(a,d[c]))}B.seal(this)};var c=B.ga.prototype;c.F=function(){if(this.type===23)this.fb=this.Ab.a.$e(this.oe,this.Ab.ta.parent);this.first&&this.first.F();this.R&&this.R.F();this.me&&this.me.F();this.Ta&&this.Ta.F();if(this.p){var a,b;for(a=0,b=this.p.length;a<b;a++)this.p[a].F()}};
c.Ug=function(a){this.k[0]=a;var b;for(a=0,b=this.p.length;a<b;a++)this.p[a].get(this.d),this.k[a+1]=this.d.data;this.U.apply(this.a.lb,this.k)};c.Qe=function(a){var b=this.Ua.w().Z();if(b.length){this.k[0]=a;var d;for(a=0,d=this.p.length;a<d;a++)this.p[a].get(this.d),this.k[a+1]=this.d.data;a=this.Ab.ac;if(this.Ta&&(this.Ta.get(this.d),this.d.O()))a=this.d.data,b=this.Ua.b;a%=b.length;a<0&&(a+=b.length);this.da>-1?this.U.apply(b[a].oa[this.da],this.k):this.U.apply(b[a],this.k)}else a.j(0)};c.Jg=
function(a){var b=this.Ua.w().Z();if(b.length){var d=this.Ab.ac;if(this.Ta&&(this.Ta.get(this.d),this.d.O())){d=this.d.data;b=this.Ua.b;d%=b.length;d<0&&(d+=b.length);d=b[d].P[this.$f];typeof d==="string"?a.S(d):a.f(d);return}d%=b.length;d<0&&(d+=b.length);d=b[d].P[this.$f];typeof d==="string"?a.S(d):a.f(d)}else a.j(0)};c.Kg=function(a){a.type=B.N.Oa;a.data=this.value};c.Gg=function(a){a.type=B.N.mb;a.data=this.value};c.Sg=function(a){a.type=B.N.Eb;a.data=this.value};c.Vg=function(a){this.first.get(a);
if(a.O())a.data=-a.data};c.Ag=function(a){this.first.get(a);this.R.get(this.d);a.O()&&this.d.O()&&(a.data+=this.d.data,this.d.ib()&&a.zb())};c.Tg=function(a){this.first.get(a);this.R.get(this.d);a.O()&&this.d.O()&&(a.data-=this.d.data,this.d.ib()&&a.zb())};c.Og=function(a){this.first.get(a);this.R.get(this.d);a.O()&&this.d.O()&&(a.data*=this.d.data,this.d.ib()&&a.zb())};c.Dg=function(a){this.first.get(a);this.R.get(this.d);a.O()&&this.d.O()&&(a.data/=this.d.data,a.zb())};c.Ng=function(a){this.first.get(a);
this.R.get(this.d);a.O()&&this.d.O()&&(a.data%=this.d.data,this.d.ib()&&a.zb())};c.Rg=function(a){this.first.get(a);this.R.get(this.d);if(a.O()&&this.d.O())a.data=Math.pow(a.data,this.d.data),this.d.ib()&&a.zb()};c.Bg=function(a){this.first.get(a);this.R.get(this.d);a.O()?this.d.xb()?a.S(a.data.toString()+this.d.data):a.data&&this.d.data?a.j(1):a.j(0):a.xb()&&(a.data+=this.d.xb()?this.d.data:(Math.round(this.d.data*1E10)/1E10).toString())};c.Qg=function(a){this.first.get(a);this.R.get(this.d);a.O()&&
this.d.O()&&(a.data||this.d.data?a.j(1):a.j(0))};c.Cg=function(a){this.first.get(a);a.data?this.R.get(a):this.me.get(a)};c.Eg=function(a){this.first.get(a);this.R.get(this.d);a.j(a.data===this.d.data?1:0)};c.Pg=function(a){this.first.get(a);this.R.get(this.d);a.j(a.data!==this.d.data?1:0)};c.Lg=function(a){this.first.get(a);this.R.get(this.d);a.j(a.data<this.d.data?1:0)};c.Mg=function(a){this.first.get(a);this.R.get(this.d);a.j(a.data<=this.d.data?1:0)};c.Hg=function(a){this.first.get(a);this.R.get(this.d);
a.j(a.data>this.d.data?1:0)};c.Ig=function(a){this.first.get(a);this.R.get(this.d);a.j(a.data>=this.d.data?1:0)};c.Fg=function(a){typeof this.fb.data==="number"?a.f(this.fb.data):a.S(this.fb.data)};B.tc=function(a,b){this.type=a||B.N.Oa;this.data=b||0;if(this.type==B.N.Oa)this.data=Math.floor(this.data);B.seal(this)};c=B.tc.prototype;c.vh=function(){return this.type===B.N.Oa};c.ib=function(){return this.type===B.N.mb};c.O=function(){return this.type===B.N.Oa||this.type===B.N.mb};c.xb=function(){return this.type===
B.N.Eb};c.Hk=function(){if(!this.vh()){if(this.ib())this.data=Math.floor(this.data);else if(this.xb())this.data=parseInt(this.data,10);this.type=B.N.Oa}};c.zb=function(){if(!this.ib()){if(this.xb())this.data=parseFloat(this.data);this.type=B.N.mb}};c.Ik=function(){if(!this.xb())this.data=this.data.toString(),this.type=B.N.Eb};c.j=function(a){this.type=B.N.Oa;this.data=Math.floor(a)};c.f=function(a){this.type=B.N.mb;this.data=a};c.S=function(a){this.type=B.N.Eb;this.data=a};c.Tk=function(a){typeof a===
"number"?(this.type=B.N.mb,this.data=a):typeof a==="string"?(this.type=B.N.Eb,this.data=a.toString()):(this.type=B.N.Oa,this.data=0)};B.N={Oa:0,mb:1,Eb:2}})();B.bc=function(c){this.a=c;this.Ca=[]};
(function(){var c=B.bc.prototype;c.o={};c.M={};c.va={};var a=c.o;a.zi=z(e);a.Be=z(e);a.gg=z(e);a.ii=function(b,a,c){return B.ra(b,a,c)};a.oi=function(b,a){var c=this.a.aa.V;if(b===0){var f=this.a.Tb();return!f.D.ag&&c>=a?f.D.ag=e:m}return B.ra(c,b,a)};a.Xi=function(b){return b?b.la:m};a.Ui=function(b,a,c){return!b?m:B.ra(b.opacity*100,a,c)};a.kj=function(b){var a=this.a.Y(),c=a.fa,f=a.Fd(),a=this.a.Yd();if(f)for(f=0;f<b;f++)this.a.Va(c.u),a.index=f,c.Wa(),this.a.xa(c.u);else for(f=0;f<b;f++)a.index=
f,c.Wa();this.a.Vd();return m};a.Ai=function(b,a,c){var f=this.a.Y(),g=f.fa,f=f.Fd(),b=this.a.Yd(b);if(f)for(;a<=c;a++)this.a.Va(g.u),b.index=a,g.Wa(),this.a.xa(g.u);else for(;a<=c;a++)b.index=a,g.Wa();this.a.Vd();return m};a.Bi=function(b){var a=b.w(),c=a.Z().slice(0),f=this.a.Y(),g=f.fa,j=f.Fd(),f=this.a.Yd(name),k;if(j)for(j=0,k=c.length;j<k;j++)this.a.Va(g.u),a=b.w(),a.s=m,a.b.length=1,a.b[0]=c[j],f.index=j,g.Wa(),this.a.xa(g.u);else{a.s=m;a.b.length=1;for(j=0,k=c.length;j<k;j++)a.b[0]=c[j],f.index=
j,g.Wa()}this.a.Vd();return m};a.hk=function(){var b=this.a.Tb(),a=b.D.lg||0,c=this.a.Qc;b.D.lg=c;return this.a.Jd||a!==c-1};a.yi=function(b){var a=this.a.Tb(),c=this.a.aa.V;return c>=(a.D.bg||0)+b?(a.D.bg=c,e):m};a.ij=function(b,a){if(!b)return m;var c=b.w(),f=c.Z(),a=Math.floor(a);if(a<0||a>=f.length)return m;f=f[a];c.s=m;c.b.length=1;c.b[0]=f;return e};a.jj=function(b){if(!b)return m;var b=b.w(),a=b.Z(),c=Math.floor(Math.random()*a.length);if(c>=a.length)return m;a=a[c];b.s=m;b.b.length=1;b.b[0]=
a;return e};a.pi=function(b,a,c){return B.ra(b.data,a,c)};a.Mi=function(b){return this.a.Zc.hasOwnProperty(b)};a.Si=function(){return typeof cr_is_preview!=="undefined"};a=c.M;a.Ci=function(b){this.a.mc=b};a.vi=function(b,a,c,f){if(a&&b)b=this.a.Ne(b,a,c,f),a=b.type.w(),a.s=m,a.b.length=1,a.b[0]=b};a.Hj=function(b,a){if(b&&b.la!=a)b.la=a,this.a.z=e};a.Fj=function(b,a){if(b&&(a=B.Je(a/100,0,1),b.opacity!=a))b.opacity=a,this.a.z=e};a.sj=function(b){this.a.A.Jc(b)};a.tj=function(b){this.a.A.Kc(b)};a.qj=
function(b,a){this.a.A.Jc(b);this.a.A.Kc(a)};a.rj=function(b){if(b=b.af())this.a.A.Jc(b.x),this.a.A.Kc(b.y)};a.Tj=function(b,a){if(b.fc===0)b.data=typeof a==="number"?a:parseFloat(a);else if(b.fc===1)b.data=a.toString()};a.bi=function(b,a){b.fc===0?b.data+=typeof a==="number"?a:parseFloat(a):b.fc===1&&(b.data+=a.toString())};a.fk=function(b,a){b.fc===0&&(b.data-=typeof a==="number"?a:parseFloat(a))};a.Bj=function(b,a){var c=this.a.Zc;switch(a){case 0:delete c[b];break;case 1:c[b]=e;break;case 2:c[b]?
delete c[b]:c[b]=e}};a.Rj=function(b){b<0&&(b=0);this.a.Rc=b};a.Kj=function(b,a){var c=a;c<0&&(c=0);if(b){var f=b.w().Z(),g,j;for(g=0,j=f.length;g<j;g++)f[g].Bc=c}};a.lj=function(b){if(!b)return m;var b=b.w().Z(),a,c;for(a=0,c=b.length;a<c;a++)b[a].Bc=-1};a.mk=function(b){if(!(b<0)){var a,c,f;a=this.a.Y();var g={};g.Vf=this.a.aa.V+b;g.Pe=a.fa;g.ma=a.ma+1;g.Oe=m;g.Bb={};g.u=[];for(b=0,a=this.a.G.length;b<a;b++)f=this.a.G[b],c=f.w(),c.s||(g.u.push(f),g.Bb[b.toString()]=c.b.slice(0));this.Ca.push(g);
return e}};a.Gj=function(b,a){if(b)b.scale=a,this.a.z=e};a=c.va;a["int"]=function(b,a){if(typeof a==="string"){if(b.j(parseInt(a,10)),isNaN(b.data))b.data=0}else b.j(a)};a["float"]=function(b,a){if(typeof a==="string"){if(b.f(parseFloat(a)),isNaN(b.data))b.data=0}else b.f(a)};a.Vk=function(b,a){typeof a==="string"?b.S(a):b.S(a.toString())};a.Bk=function(b,a){b.j(a.length||0)};a.random=function(b,a,c){c===void 0?b.f(Math.random()*a):b.f(Math.random()*(c-a)+a)};a.sqrt=function(b,a){b.f(Math.sqrt(a))};
a.abs=function(b,a){b.f(Math.abs(a))};a.round=function(b,a){b.j(Math.round(a))};a.floor=function(b,a){b.j(Math.floor(a))};a.ceil=function(b,a){b.j(Math.ceil(a))};a.sin=function(b,a){b.f(Math.sin(B.J(a)))};a.cos=function(b,a){b.f(Math.cos(B.J(a)))};a.tan=function(b,a){b.f(Math.tan(B.J(a)))};a.asin=function(b,a){b.f(B.Cb(Math.asin(a)))};a.acos=function(b,a){b.f(B.Cb(Math.acos(a)))};a.atan=function(b,a){b.f(B.Cb(Math.atan(a)))};a.exp=function(b,a){b.f(Math.exp(a))};a.Ck=function(b,a){b.f(Math.log(a))};
a.Dk=function(b,a){b.f(Math.log(a)/Math.LN10)};a.max=function(b){var a=arguments[1],c,f;for(c=2,f=arguments.length;c<f;c++)a<arguments[c]&&(a=arguments[c]);b.f(a)};a.min=function(b){var a=arguments[1],c,f;for(c=2,f=arguments.length;c<f;c++)a>arguments[c]&&(a=arguments[c]);b.f(a)};a.sb=function(b){b.f(this.a.sb)};a.Rc=function(b){b.f(this.a.Rc)};a.$k=function(b){b.f((Date.now()-this.a.Nc)/1E3)};a.Vf=function(b){b.f(this.a.aa.V)};a.Qc=function(b){b.j(this.a.Qc)};a.Dc=function(b){b.j(this.a.Dc)};a.xd=
function(b){b.j(this.a.xd)};a.Ek=function(b,a){if(this.a.yb.length)if(a){var c,f;for(c=0,f=this.a.yb.length;c<f;c++){var g=this.a.yb[c];if(g.name===a){b.j(g.index);return}}b.j(0)}else b.j(this.a.Ye().index);else b.j(0)};a.tk=function(b,a,c,f,g){b.f(B.Ob(a,c,f,g))};a.e=function(b,a,c,f,g){b.f(B.Cb(B.ic(a,c,f,g)))};a.Rk=function(b){b.f(this.a.A.scrollX)};a.Sk=function(b){b.f(this.a.A.scrollY)};a.Lk=function(b){b.S("\n")};a.uf=function(b,a,c,f){b.f(B.uf(a,c,f))};a.bl=function(b){b.j(this.a.width)};a.al=
function(b){b.j(this.a.height)};a.Zk=function(b,a){b.S(a.toUpperCase())};a.Gk=function(b,a){b.S(a.toLowerCase())};a.Je=function(b,a,c,f){a<c?b.f(c):a>f?b.f(f):b.f(a)};a.yk=function(b,a){var c=this.a.bf(a);c?b.f(c.scale):b.f(0)};a.xk=function(b,a){var c=this.a.bf(a);c?b.f(c.opacity*100):b.f(0)};a.Ak=function(b){b.j(this.a.A.width)};a.zk=function(b){b.j(this.a.A.height)};a.find=function(b,a,c){b.j(a.search(RegExp(B.Ef(c),"i")))};a.left=function(b,a,c){b.S(a.substr(0,c))};a.right=function(b,a,c){b.S(a.substr(a.length-
c))};a.Jk=function(b,a,c,f){b.S(a.substr(c,f))};a.Xk=function(b,a,c,f){a=a.split(f);c=Math.floor(c);c<0||c>=a.length?b.S(""):b.S(a[c])};a.Yk=function(b,a,c){b.j(a.split(c).length)};a.replace=function(b,a,c,f){b.S(a.replace(RegExp(B.Ef(c),"gi"),f))};a.trim=function(b,a){b.S(a.trim())};a.Ok=function(a){a.f(Math.PI)};c.Gh=function(){var a,c,o,f,g,j=this.a.Y();for(a=0,o=this.Ca.length;a<o;a++)if(f=this.Ca[a],!(f.Vf>this.a.aa.V)){j.fa=f.Pe;j.ma=f.ma;j.pa=0;for(c in f.Bb)if(f.Bb.hasOwnProperty(c))g=this.a.G[parseInt(c,
10)].w(),g.s=m,g.b=f.Bb[c];f.Pe.Fh();this.a.od(f.u);f.Oe=e}for(a=0,c=0,o=this.Ca.length;a<o;a++)f=this.Ca[a],this.Ca[c]=f,f.Oe||c++;this.Ca.length=c}})();
B.mg=function(c){var a=c[0].prototype,b=c[1],d=c[3],o=c[4],f=c[5],g=c[6],c=c[7];if(!a.o)a.o={};if(!a.M)a.M={};if(!a.va)a.va={};var j=a.o,k=a.M,a=a.va;if(d)j.ri=function(a,b){return B.ra(this.x,a,b)},j.si=function(a,b){return B.ra(this.y,a,b)},j.Oi=function(){var a=this.m;if(!this.la||!a.la)return m;this.Ba();var b=this.X;return!(b.right<a.qe||b.bottom<a.se||b.left>a.re||b.top>a.pe)},j.Pi=function(){this.Ba();var a=this.X,b=this.a.A;return a.right<0||a.bottom<0||a.left>b.width||a.top>b.height},j.hj=
function(a,b,c){var d=this.w(),f=d.Z();if(!f.length)return m;var g=f[0],k=g,j=B.Ob(g.x,g.y,b,c),o,u,A;for(o=1,u=f.length;o<u;o++)if(g=f[o],A=B.Ob(g.x,g.y,b,c),a===0&&A<j||a===1&&A>j)j=A,k=g;d.s=m;d.b.length=1;d.b[0]=k;return e},k.Xj=function(a){if(this.x!==a)this.x=a,this.n()},k.Yj=function(a){if(this.y!==a)this.y=a,this.n()},k.Nj=function(a,b){if(this.x!==a||this.y!==b)this.x=a,this.y=b,this.n()},k.Oj=function(a,b){var c=a.ah(this);if(c){var d;c.hb?(d=c.hb(b,e),c=c.hb(b,m)):(d=c.x,c=c.y);if(this.x!==
d||this.y!==c)this.x=d,this.y=c,this.n()}},k.$i=function(a){a!==0&&(this.x+=Math.cos(this.e)*a,this.y+=Math.sin(this.e)*a,this.n())},k.Zi=function(a,b){b!==0&&(this.x+=Math.cos(B.J(a))*b,this.y+=Math.sin(B.J(a))*b,this.n())},a.ok=function(a){a.f(this.x)},a.pk=function(a){a.f(this.y)},a.sb=function(a){a.f(this.a.Ze(this))};if(o)j.qi=function(a,b){return B.ra(this.width,a,b)},j.ki=function(a,b){return B.ra(this.height,a,b)},k.Wj=function(a){a<0&&(a=-a);if(this.width!==a)this.width=a,this.n()},k.Cj=
function(a){a<0&&(a=-a);if(this.height!==a)this.height=a,this.n()},k.Pj=function(a,b){var c=a,d=b;c<0&&(c=-c);d<0&&(d=-d);if(this.width!==c||this.height!==d)this.width=c,this.height=d,this.n()},a.nk=function(a){a.f(this.width)},a.Di=function(a){a.f(this.height)};if(f)j.di=function(a,b){return B.ad(this.e,B.J(b))<=B.J(a)},j.Li=function(a){return B.Gb(this.e,B.J(a))},j.Ji=function(a,b){var c=B.Wf(b),d=B.C(this.e);return B.Gb(d,B.Wf(a))&&!B.Gb(d,c)},k.vj=function(a){a=B.J(B.Ke(a));if(!isNaN(a)&&this.e!==
a)this.e=a,this.n()},k.mj=function(a){if(a!==0&&!isNaN(a))this.e+=B.J(a),this.e=B.C(this.e),this.n()},k.nj=function(a){if(a!==0&&!isNaN(a))this.e-=B.J(a),this.e=B.C(this.e),this.n()},k.oj=function(a,b){var c=B.Fe(this.e,B.J(b),B.J(a));if(!isNaN(c)&&this.e!==c)this.e=c,this.n()},k.pj=function(a,b,c){a=B.Fe(this.e,Math.atan2(c-this.y,b-this.x),B.J(a));if(!isNaN(a)&&this.e!==a)this.e=a,this.n()},k.Sj=function(a,b){var c=Math.atan2(b-this.y,a-this.x);if(!isNaN(c)&&this.e!==c)this.e=c,this.n()},a.ci=function(a){a.f(B.Lh(this.e))};
if(!b)j.li=function(a,b,c){return B.ra(this.P[a],b,c)},j.Ki=function(a){return this.P[a]},j.gj=function(a){return this.Uc===a},k.Ej=function(a,b){typeof this.P[a]==="number"?this.P[a]=typeof b==="number"?b:parseFloat(b):typeof this.P[a]==="string"&&(this.P[a]=typeof b==="string"?b:b.toString())},k.ai=function(a,b){typeof this.P[a]==="number"?this.P[a]+=typeof b==="number"?b:parseFloat(b):typeof this.P[a]==="string"&&(this.P[a]+=typeof b==="string"?b:b.toString())},k.ek=function(a,b){typeof this.P[a]===
"number"&&(this.P[a]-=typeof b==="number"?b:parseFloat(b))},k.zj=function(a,b){this.P[a]=b},k.gk=function(a){this.P[a]=!this.P[a]},k.xi=function(){this.a.xe(this)},a.ti=function(a){a.j(this.type.b.length)},a.ik=function(a){a.j(this.Uc)};if(g)j.Ti=y("la"),k.Uj=function(a){if(!a!==!this.la)this.la=a,this.a.z=e},j.mi=function(a,b){return B.ra(this.opacity*100,a,b)},k.Lj=function(a){a/=100;a<0?a=0:a>1&&(a=1);if(a!==this.opacity)this.opacity=a,this.a.z=e},a.fj=function(a){a.f(this.opacity*100)};if(c)k.cj=
function(){var a=this.Ub();if(a!==this.m.b.length-1)B.Hb(this.m.b,a),this.m.b.push(this),this.a.z=e,this.m.$a=e},k.aj=function(){var a=this.Ub();if(a!==0)B.Hb(this.m.b,a),this.m.b.unshift(this),this.a.z=e,this.m.$a=e},k.bj=function(a){if(a&&a!=this.m)B.Hb(this.m.b,this.Ub()),this.m.$a=e,this.m=a,this.ue=a.b.length,a.b.push(this),this.a.z=e},a.Wi=function(a){a.j(this.m.zf)},a.Vi=function(a){a.S(this.m.name)},a.qk=function(a){a.j(this.Ub())}};
B.n=function(){this.ed=e;this.a.z=e;var c,a;for(c=0,a=this.kc.length;c<a;c++)this.kc[c](this)};B.$c=function(c){c&&this.kc.push(c)};B.Ba=function(){if(this.ed)this.X.set(this.x,this.y,this.x+this.width,this.y+this.height),this.X.offset(-this.Ka*this.width,-this.$*this.height),!this.e||this.e===0?this.Aa.de(this.X):(this.X.offset(-this.x,-this.y),this.Aa.Jh(this.X,this.e),this.Aa.offset(this.x,this.y),this.Aa.pg(this.X)),this.ed=m};
B.ph=function(c,a){if(!this.X.qa(c,a))return m;return!this.Aa.qa(c,a)?m:this.ea&&!this.ea.Gd()?(this.ea.ld(this.width,this.height*(this.a.wb(this)?-1:1),this.e),this.ea.qa(c-this.x,a-this.y)):e};B.nf=function(){this.type.Vh();return this.Dd};B.qh=function(){this.m.Wh();return this.ue};B.of=function(){return"inst:"+this.type.name+"#"+this.Uc};B.Ph=function(){var c=this.w().Z();return c.length?c[0]:i};B.Qh=function(c){var a=this.w().Z();return a.length?a[c.gf()%a.length]:i};
B.Uh=function(){if(this.ke){var c,a;for(c=0,a=this.b.length;c<a;c++)this.b[c].Dd=c;this.ke=m}};B.Oh=function(){return this.Xa[this.Ia]};B.Sh=function(){this.Ia++;this.Ia===this.Xa.length?this.Xa.push(new B.selection(this)):this.Xa[this.Ia].s=e};B.Th=function(){this.Ia++;this.Ia===this.Xa.length&&this.Xa.push(new B.selection(this));var c=this.Xa[this.Ia],a=this.Xa[this.Ia-1];a.s?c.s=e:(c.s=m,c.b=a.b.slice(0))};B.Rh=function(){this.Ia--};
B.Mh=function(c){var a,b;for(a=0,b=this.h.length;a<b;a++)if(c===this.h[a].name)return this.h[a];return i};B.Nh=function(c){var a,b;for(a=0,b=this.h.length;a<b;a++)if(c===this.h[a].name)return a;return-1};B.ra=function(c,a,b){switch(a){case 0:return c===b;case 1:return c!==b;case 2:return c<b;case 3:return c<=b;case 4:return c>b;case 5:return c>=b;default:return m}};B.i.ab=v("a");
(function(){var c=B.i.ab.prototype;c.L=function(a){this.kb=a;this.a=a.a};c.L.prototype.t=q();var a=i,b=i,d="";c.B=function(c){this.type=c;a=this.a=c.a;b=this;this.Ib=[];this.Wb=i;this.Xh=!!(new Audio).canPlayType('audio/ogg; codecs="vorbis"')};var o=c.B.prototype;o.t=q();o.Xe=function(c){var f,k,h;for(f=0,k=this.Ib.length;f<k;f++)if(h=this.Ib[f],h.qg===c&&(h.ended||h.hd||h.jd))return h;h=new Audio;h.kd="";h.qg=c;h.src=c+(this.Xh?".ogg":".m4a");h.addEventListener("ended",function(c){return function(){d=
c.kd;a.trigger(B.i.ab.prototype.o.dg,b)}}(h));this.Ib.push(h);return h};var f=[];o.Sb=function(a){f.length=0;if(a.length){var b,c,d;for(b=0,c=this.Ib.length;b<c;b++)d=this.Ib[b],a.toLowerCase()===d.kd.toLowerCase()&&f.push(d)}else if(this.Wb&&!this.Wb.ended)f.length=1,f[0]=this.Wb};c.o={};c.o.dg=function(a){return d.toLowerCase()===a.toLowerCase()};c.M={};o=c.M;o.Play=function(a,b){var c=this.Wb=this.Xe(this.a.wd+a);c.kd=b;c.hd=m;c.playbackRate=1;c.volume=1;c.loop=m;c.muted=m;if(c.jd)c.currentTime=
0,c.jd=m;c.play()};o.jg=function(a,b){this.Sb(a);var c,d;for(c=0,d=f.length;c<d;c++)f[c].loop=b===0};o.Jj=function(a,b){this.Sb(a);var c,d;for(c=0,d=f.length;c<d;c++)f[c].muted=b===0};o.Vj=function(a,b){this.Sb(a);var c=Math.pow(10,b/20);c<0&&(c=0);c>1&&(c=1);var d,n;for(d=0,n=f.length;d<n;d++){if(!f[d].volume)break;f[d].volume=c}};o.hg=function(a){a=this.Xe(this.a.wd+a);if(typeof a.hd==="undefined")a.Qk="auto",a.hd=e};o.Mj=function(a,b){this.Sb(a);b<0&&(b=0);var c,d;for(c=0,d=f.length;c<d;c++)f[c].playbackRate=
b};o.kg=function(a){this.Sb(a);var b;for(a=0,b=f.length;a<b;a++)f[a].pause(),f[a].jd=e};c.va={}})();B.i.Da=v("a");
(function(){var c=B.i.Da.prototype;c.L=function(a){this.kb=a;this.a=a.a};c.L.prototype.t=q();c.B=function(a){this.type=a;this.a=a.a;this.xc=Array(256);this.Sc=0;this.pc=m};var a=c.B.prototype;a.t=function(){jQuery(document).keydown(function(a){return function(c){a.Nd(c)}}(this));jQuery(document).keyup(function(a){return function(c){a.Od(c)}}(this))};a.Nd=function(a){if(!this.xc[a.which])this.xc[a.which]=e,this.pc=this.a.trigger(B.i.Da.prototype.o.cg,this),this.Sc=a.which,this.a.trigger(B.i.Da.prototype.o.eg,
this),this.pc&&a.preventDefault()};a.Od=function(a){this.xc[a.which]=m;this.Sc=a.which;this.a.trigger(B.i.Da.prototype.o.fg,this)};c.o={};c=c.o;c.Xc=function(a){return this.xc[a]};c.eg=function(a){a=a===this.Sc;this.pc=this.pc||a;return a};c.cg=z(e);c.fg=function(a){return a===this.Sc}})();B.i.K=v("a");
(function(){function c(a,b,c){var d,h=0,n,l;for(d=0,n=a.length;d<n;d++)l=a[d],l[0]===b&&l[1]===c||l[0]===c&&l[1]===b||(a[h]=a[d],h++);a.length=h}function a(a,b,c){var d,h,n;for(d=0,h=a.length;d<h;d++)if(n=a[d],n[0]===b&&n[1]===c||n[0]===c&&n[1]===b)return e;return m}var b=B.i.K.prototype;b.L=function(a){this.kb=a;this.a=a.a};b.L.prototype.t=function(){var a,b,c,d,h,n;for(a=0,b=this.na.length;a<b;a++){h=this.na[a];h.name=h[0];h.speed=h[1];h.loop=h[2];h.Gf=h[3];h.Ic=h[4];h.Sd=h[5];h.frames=h[6];for(c=
0,d=h.frames.length;c<d;c++)n=h.frames[c],n.Sf=n[0],n.Tf=n[1],n.duration=n[2],n.Ka=n[3],n.$=n[4],n.Ed=n[5],n.Cf=n[6],n.T=new Image,n.T.src=n[0],n.T.Me=n[1],n.uc=i,this.a.gc.push(n.T),B.seal(n);B.seal(h)}};b.B=function(a){this.type=a;this.a=a.a;this.ea=new B.Wc(this.type.na[0].frames[0].Cf)};var d=b.B.prototype;d.Pb=function(a){return a<=0||a>=11?"source-over":"lighter,xor,copy,destination-over,source-in,destination-in,source-out,destination-out,source-atop,destination-atop".split(",")[a-1]};d.t=function(){this.la=
this.I[0]===0;this.bb=this.Pb(this.I[2]);this.dd=this.I[3]===1;this.cd=this.I[3]===2;this.La=m;if(!(this.type.na.length===1&&this.type.na[0].frames.length===1)&&this.type.na[0].speed!==0)this.a.cc(this),this.La=e;this.v=this.type.na[0];this.g=this.I[1];if(this.g<0)this.g=0;if(this.g>=this.v.frames.length)this.g=this.v.frames.length-1;this.Mb=this.type.na[0].speed;this.gb=this.a.aa.V;this.pb=e;this.jc=0;this.ob=e;this.rb=this.bd="";this.Ie=0;this.qb=-1;if(this.a.wb(this))this.$=1-this.$;if(this.dd||
this.cd){this.Eh||this.$c(function(a){return function(){a.Ch()}}(this));var a,b,c,d,h,n;for(a=0,b=this.type.na.length;a<b;a++){h=this.type.na[a];for(c=0,d=h.frames.length;c<d;c++)if(n=h.frames[c],!n.uc)n.uc=this.a.Wg(n.T)}}this.Eh=e};d.Ch=function(){this.$=this.v.frames[this.g].$;if(this.a.wb(this))this.$=1-this.$};d.za=function(){this.rb.length&&this.xg();this.qb>=0&&this.yg();var a=this.a.aa.V,b=this.v,c=b.frames[this.g],d=c.duration/this.Mb;if(this.pb&&a>=this.gb+d){this.ob?this.g++:this.g--;this.gb+=
d;if(this.g>=b.frames.length)if(b.loop)b.Sd?(this.ob=m,this.g=b.frames.length-2):this.g=b.Ic;else if(this.jc++,this.jc>=b.Gf){if(this.g=b.frames.length-1,this.bd=b.name,this.a.trigger(B.i.K.prototype.o.Ae,this),this.a.trigger(B.i.K.prototype.o.ze,this),!this.rb.length&&this.qb===-1)this.pb=m}else b.Sd?(this.ob=m,this.g=b.frames.length-2):this.g=b.Ic;if(this.g<0)if(b.Sd)this.g=1,this.ob=e;else if(b.loop)this.g=b.Ic;else if(this.jc++,this.jc>=b.Gf){if(this.g=0,this.bd=b.name,this.a.trigger(B.i.K.prototype.o.Ae,
this),this.a.trigger(B.i.K.prototype.o.ze,this),!this.rb.length&&this.qb===-1)this.pb=m}else this.g=b.Ic;if(this.g<0)this.g=0;else if(this.g>=b.frames.length)this.g=b.frames.length-1;if(a>this.gb+b.frames[this.g].duration/this.Mb)this.gb=this.a.aa.V;a=b.frames[this.g];this.nb(c,a);this.a.z=e}};d.xg=function(){var a=this.v.frames[this.g],b,c,d,h=i;for(b=0,c=this.type.na.length;b<c;b++)if(d=this.type.na[b],d.name.toLowerCase()===this.rb.toLowerCase()){h=d;break}this.rb="";if(h&&h.name.toLowerCase()!==
this.v.name.toLowerCase()){this.v=h;this.Mb=h.speed;if(this.g<0)this.g=0;if(this.g>=this.v.frames.length)this.g=this.v.frames.length-1;if(this.Ie===1)this.g=0;this.pb=e;this.gb=this.a.aa.V;this.ob=e;this.nb(a,this.v.frames[this.g]);this.a.z=e}};d.yg=function(){var a=this.v.frames[this.g],b=this.g;this.g=Math.floor(this.qb);if(this.g<0)this.g=0;if(this.g>=this.v.frames.length)this.g=this.v.frames.length-1;if(b!==this.g)this.nb(a,this.v.frames[this.g]),this.gb=this.a.aa.V,this.a.z=e;this.qb=-1};d.nb=
function(a,b){var c=a.T.width,d=a.T.height,h=b.T.width,n=b.T.height;c!=h&&(this.width*=h/c);d!=n&&(this.height*=n/d);this.Ka=b.Ka;this.$=b.$;this.ea.Lf(b.Cf);this.n();this.a.trigger(B.i.K.prototype.o.nb,this)};d.Ra=function(a){if(this.opacity!==1)a.globalAlpha=this.opacity;if(this.bb!=="source-over")a.globalCompositeOperation=this.bb;var b=this.v.frames[this.g],c=b.T;if(this.dd){var d=B.C(this.e);if(d>Math.PI/2&&d<=Math.PI*3/2)c=b.uc}if(this.cd&&(d=B.C(this.e),d>=Math.PI))c=b.uc;b=this.x;d=this.y;
this.a.Td&&(b=Math.round(b),d=Math.round(d));this.e===0?a.drawImage(c,b-this.Ka*this.width,d-this.$*this.height,this.width,this.height):(a.save(),a.translate(b,d),a.rotate(this.e),a.drawImage(c,0-this.Ka*this.width,0-this.$*this.height,this.width,this.height),a.restore());if(this.bb!=="source-over")a.globalCompositeOperation="source-over";if(this.opacity!==1)a.globalAlpha=1};d.$g=function(a){var b=this.v.frames[this.g],c,d;for(c=0,d=b.Ed.length;c<d;c++)if(a.toLowerCase()===b.Ed[c][0].toLowerCase())return c;
return-1};d.hb=function(a,b){var c=this.v.frames[this.g],d=c.Ed,h;h=typeof a==="string"?this.$g(a):a-1;h=Math.floor(h);if(h<0||h>=d.length)return b?this.x:this.y;var n=(d[h][1]-c.Ka)*this.width,d=d[h][2];this.a.wb(this)&&(d=1-d);d=(d-c.$)*this.height;c=Math.cos(this.e);h=Math.sin(this.e);var l=n*c-d*h,d=d*c+n*h,n=l;n+=this.x;d+=this.y;return b?n:d};b.o={};d=b.o;d.ej=function(b){if(!b)return m;var d=this.a,j=d.Tb(),k=j.type;if(!j.D.Lb)j.D.Lb=[],d.De(function(a){return function(b){var c,d=0,f,g;for(c=
0,f=a.length;c<f;c++)g=a[c],g[0]!==b&&g[1]!==b&&(a[d]=a[c],d++);a.length=d}}(j.D.Lb));var h=k.w(),n=b.w(),l=h.Z(),o=n.Z(),r,s,t,w,x,u;h.s=m;h.b.length=1;n.s=m;n.b.length=1;var A=d.Y().fa;for(r=0,s=l.length;r<s;r++){t=l[r];for(w=0,x=o.length;w<x;w++)if(u=o[w],d.Ya(t,u)||d.sg(t,u)){if(!a(j.D.Lb,t,u))j.D.Lb.push([t,u]),k===b?(h.b.length=2,h.b[0]=t,h.b[1]=u):(h.b[0]=t,n.b[0]=u),d.Va(A.u),A.Wa(),d.xa(A.u)}else c(j.D.Lb,t,u)}return m};var o=[];d.Qi=function(b){if(!b)return m;var c=this.a,d=c.Tb(),k=d.type,
h=k.w(),n=b.w(),l=h.Z(),p=n.Z(),r,s,t,w,x;if(d.wc){k=[];for(d=0,r=l.length;d<r;d++){s=l[d];b=m;for(t=0,w=p.length;t<w;t++)if(x=p[t],c.Ya(s,x)){b=e;break}b||k.push(s)}h.s=m;h.b=k;return h.b.length}else{h.s=m;h.b.length=1;n.s=m;n.b.length=1;var u=c.Y().fa;o.length=0;for(d=0,r=l.length;d<r;d++){s=l[d];for(t=0,w=p.length;t<w;t++)if(x=p[t],c.Ya(s,x)){if(k===b)if(a(o,s,x))continue;else o.push([s,x]),h.b.length=2,h.b[0]=s,h.b[1]=x;else h.b[0]=s,n.b[0]=x;c.Va(u.u);u.Wa();c.xa(u.u)}}return m}};d.Ii=function(a){return this.v.name.toLowerCase()===
a.toLowerCase()};d.ji=function(a,b){return B.ra(this.g,a,b)};d.ze=function(a){return this.bd.toLowerCase()===a.toLowerCase()};d.Ae=z(e);d.nb=z(e);b.M={};d=b.M;d.ak=function(a,b,c){if(a&&b){b=this.a.Ne(a,b,this.hb(c,e),this.hb(c,m));b.e=this.e;b.n();var d=this.a.Zg(),c=m;if(typeof d.D.Ce==="undefined"||d.D.Ce<this.a.Qb)c=e,d.D.Ce=this.a.Qb;a=a.w();a.s=m;c?(a.b.length=1,a.b[0]=b):a.b.push(b)}};d.ig=function(a){this.bb=this.Pb(a);this.a.z=e};d.dk=function(){this.pb=m};d.ck=function(a){this.pb=e;this.gb=
this.a.aa.V;if(a===1&&this.g!==0)a=this.v.frames[this.g],this.g=0,this.nb(a,this.v.frames[0]),this.a.z=e;if(!this.La)this.a.cc(this),this.La=e};d.wj=function(a,b){this.rb=a;this.Ie=b;if(!this.La)this.a.cc(this),this.La=e};d.xj=function(a){this.qb=a;if(!this.La)this.a.cc(this),this.La=e};d.yj=function(a){this.Mb=Math.abs(a);this.ob=a>=0;if(!this.La)this.a.cc(this),this.La=e};b.va={};b=b.va;b.ei=function(a){a.j(this.g)};b.fi=function(a){a.j(this.v.frames.length)};b.gi=function(a){a.S(this.v.name)};
b.hi=function(a){a.f(this.Mb)};b.Fi=function(a,b){a.f(this.hb(b,e))};b.Gi=function(a,b){a.f(this.hb(b,m))};b.Hi=function(a){a.f(this.v.frames[this.g].T.width)};b.Ei=function(a){a.f(this.v.frames[this.g].T.height)}})();B.i.hc=v("a");
(function(){var c=B.i.hc.prototype;c.L=function(a){this.kb=a;this.a=a.a};c.L.prototype.t=function(){this.T=new Image;this.T.src=this.Sf;this.T.Me=this.Tf;this.a.gc.push(this.T);this.pattern=i};c.B=function(a){this.type=a;this.a=a.a};var a=c.B.prototype;a.Pb=function(a){return a<=0||a>=11?"source-over":"lighter,xor,copy,destination-over,source-in,destination-in,source-out,destination-out,source-atop,destination-atop".split(",")[a-1]};a.t=function(){this.la=this.I[0]===0;this.bb=this.Pb(this.I[1])};
a.Ra=function(a){if(!this.type.pattern)this.type.pattern=a.createPattern(this.type.T,"repeat");a.save();a.globalAlpha=this.opacity;a.globalCompositeOperation=this.bb;a.fillStyle=this.type.pattern;var c=this.x,o=this.y;this.a.Td&&(c=Math.round(c),o=Math.round(o));var f=-(this.Ka*this.width)%this.type.T.width,g=-(this.$*this.height)%this.type.T.height;a.translate(c+f,o+g);this.e!==0&&a.rotate(this.e);a.fillRect(-f-this.Ka*this.width,-g-this.$*this.height,this.width,this.height);a.restore()};c.o={};
c.M={};c.M.ig=function(a){this.bb=this.Pb(a);this.a.z=e};c.va={}})();B.h.ve=v("a");
(function(){var c=B.h.ve.prototype;c.L=function(a,c){this.l=a;this.Ec=c;this.a=a.a};c.L.prototype.t=q();c.B=function(a,c){this.type=a;this.l=a.l;this.c=c;this.a=a.a;this.he=this.ge=this.fe=this.ie=this.jf=this.$d=this.Ld=this.rd=this.ne=m;this.r=0;this.ha=this.ca=this.c.e};var a=c.B.prototype;a.t=function(){this.ba=this.I[0];this.Fb=this.I[1];this.cb=this.I[2];this.Qf=B.J(this.I[3]);this.zg=B.J(this.I[4]);this.Yg=this.I[5];this.ce=this.I[6]===1;this.wg=this.I[7]===1;this.qf=this.c.x;this.rf=this.c.y;
this.yc=this.c.e;this.wg&&(jQuery(document).keydown(function(a){return function(c){a.Nd(c)}}(this)),jQuery(document).keyup(function(a){return function(c){a.Od(c)}}(this)))};a.Nd=function(a){switch(a.which){case 37:a.preventDefault();this.Ld=e;break;case 38:a.preventDefault();this.ne=e;break;case 39:a.preventDefault();this.$d=e;break;case 40:a.preventDefault(),this.rd=e}};a.Od=function(a){switch(a.which){case 37:a.preventDefault();this.Ld=m;break;case 38:a.preventDefault();this.ne=m;break;case 39:a.preventDefault();
this.$d=m;break;case 40:a.preventDefault(),this.rd=m}};a.za=function(){var a=this.a.Ze(this.c),c=this.Ld||this.ge,o=this.$d||this.he,f=this.ne||this.ie,g=this.rd||this.fe;this.fe=this.ie=this.he=this.ge=m;if(this.ce&&this.c.e!==this.yc)this.yc=this.ha=this.ca=this.c.e;var j=this.a.Za(this.c);if(j&&(this.a.Ff(this.c,j),!this.a.Zd(this.c)))return;this.jf&&(g=f=o=c=m);if(f&&!g&&(this.r+=this.Fb*a,this.r>this.ba))this.r=this.ba;if(g&&!f&&(this.r-=this.cb*a,this.r<-this.ba))this.r=-this.ba;if(g===f)if(this.r>
0){if(this.r-=this.cb*a*0.1,this.r<0)this.r=0}else if(this.r<0&&(this.r+=this.cb*a*0.1,this.r>0))this.r=0;this.r<0&&(f=c,c=o,o=f);if(c&&!o)this.ca=B.C(this.ca-this.Qf*a*(Math.abs(this.r)/this.ba));if(o&&!c)this.ca=B.C(this.ca+this.Qf*a*(Math.abs(this.r)/this.ba));c=this.zg*a;o=B.ad(this.ca,this.ha);o>B.J(90)&&(c+=o-B.J(90));this.ha=o<=c?B.C(this.ca):B.Gb(this.ca,this.ha)?B.C(this.ha+c):B.C(this.ha-c);this.qf=this.c.x;this.rf=this.c.y;if(this.r!==0&&a!==0){this.c.x+=Math.cos(this.ha)*this.r*a;this.c.y+=
Math.sin(this.ha)*this.r*a;if(this.ce)this.yc=this.c.e=this.ca;this.c.n();if(c=this.a.Za(this.c))this.a.Ff(this.c,c),this.r=Math.abs(this.r),this.ha=this.a.rg(this.c,this.qf,this.rf),this.c.x+=Math.cos(this.ha)*this.r*a,this.c.y+=Math.sin(this.ha)*this.r*a,this.c.n(),this.r*=1-this.Yg,this.a.Dh(this.c,Math.cos(this.ha),Math.sin(this.ha),Math.max(this.r*2.5*a,30))||this.a.Zd(this.c,100)}else if(this.ce&&this.c.e!==this.ca)this.yc=this.c.e=this.ca,this.c.n(),this.a.Za(this.c)&&this.a.Zd(this.c,100)};
c.o={};a=c.o;a.Ni=function(){return this.r!==0};a.ni=function(a,c){return B.ra(this.r,a,c)};c.M={};a=c.M;a.kg=function(){this.r=0};a.Dj=v("jf");a.Qj=function(a){a<-this.ba&&(a=-this.ba);if(a>this.ba)a=this.ba;this.r=a};a.Ij=function(a){this.ba=a;if(this.ba<0)this.ba=0};a.uj=function(a){this.Fb=a;if(this.Fb<0)this.Fb=0};a.Aj=function(a){this.cb=a;if(this.cb<0)this.cb=0};a.$j=function(a){switch(a){case 0:this.ge=e;break;case 1:this.he=e;break;case 2:this.ie=e;break;case 3:this.fe=e}};c.va={};c=c.va;
c.bk=function(a){a.f(Math.sqrt(this.sd*this.sd+this.td*this.td))};c.Yi=function(a){a.f(this.ba)};c.$h=function(a){a.f(this.Fb)};c.wi=function(a){a.f(this.cb)};c.dj=function(a){a.f(B.Cb(Math.atan2(this.td,this.sd)))};c.kk=function(a){a.f(this.sd)};c.lk=function(a){a.f(this.td)}})();B.h.Yc=v("a");
(function(){var c=B.h.Yc.prototype;c.L=function(a,c){this.l=a;this.Ec=c;this.a=a.a};c.L.prototype.t=q();c.B=function(a,c){this.type=a;this.l=a.l;this.c=c;this.a=a.a};var a=c.B.prototype;a.t=function(){this.sa=i;this.Uf=this.yf=this.Rd=this.Qd=0;this.a.De(function(a){return function(c){a.Ah(c)}}(this))};a.Ah=function(a){if(this.sa==a)this.sa=i};a.Fc=function(){this.sa=i};a.za=function(){if(this.sa){var a=this.sa.x+Math.cos(this.sa.e+this.Qd)*this.Rd,c=this.sa.y+Math.sin(this.sa.e+this.Qd)*this.Rd,
o=B.C(this.yf+(this.sa.e-this.Uf));if(this.c.x!==a||this.c.y!==c||this.c.e!==o)this.c.x=a,this.c.y=c,this.c.e=o,this.c.n()}};c.o={};c.o.Ri=function(){return!!this.sa};c.M={};a=c.M;a.Yc=function(a){if(a&&(a=a.af()))this.sa=a,this.Qd=B.ic(a.x,a.y,this.c.x,this.c.y)-a.e,this.Rd=B.Ob(a.x,a.y,this.c.x,this.c.y),this.yf=this.c.e,this.Uf=a.e};a.jk=function(){this.sa=i};c.va={}})();B.h.bound=v("a");
(function(){var c=B.h.bound.prototype;c.L=function(a,b){this.l=a;this.Ec=b;this.a=a.a};c.L.prototype.t=q();c.B=function(a,b){this.type=a;this.l=a.l;this.c=b;this.a=a.a;this.mode=0};c=c.B.prototype;c.t=function(){this.mode=this.I[0]};c.za=function(){this.c.Ba();var a=this.c.X,b=this.c.m.wa,c=m;if(this.mode===0){if(this.c.x<0)this.c.x=0,c=e;if(this.c.y<0)this.c.y=0,c=e;if(this.c.x>b.width)this.c.x=b.width,c=e;if(this.c.y>b.height)this.c.y=b.height,c=e}else a.left<0&&(this.c.x-=a.left,c=e),a.top<0&&
(this.c.y-=a.top,c=e),a.right>b.width&&(this.c.x-=a.right-b.width,c=e),a.bottom>b.height&&(this.c.y-=a.bottom-b.height,c=e);c&&this.c.n()}})();B.h.Jf=function(c){this.a=c;this.Nf=this.ee=this.$b=this.Mf=0};
(function(){var c=B.h.Jf.prototype;c.L=function(a,c){this.l=a;this.Ec=c;this.a=a.a};c.L.prototype.t=q();c.B=function(a,c){this.type=a;this.l=a.l;this.c=c;this.a=a.a};var a=c.B.prototype;a.t=q();a.za=function(){var a=this.l.Xb.ec(),c=0,o=0,f,g;for(f=0,g=a.length;f<g;f++)c+=a[f].x,o+=a[f].y;f=this.c.m.wa;var j=this.a.aa.V,k=g=0;if(j>=this.l.$b&&j<this.l.ee)g=this.l.Mf,this.l.Nf===0&&(g*=1-(j-this.l.$b)/(this.l.ee-this.l.$b)),j=Math.random()*Math.PI*2,k=Math.random()*g,g=Math.cos(j)*k,k*=Math.sin(j);
f.Jc(c/a.length+g);f.Kc(o/a.length+k)};c.M={};c.M.Zj=function(a,c,o){this.l.Mf=a;this.l.$b=this.a.aa.V;this.l.ee=this.l.$b+c;this.l.Nf=o}})();B.h.ia=v("a");(function(){var c=B.h.ia.prototype;c.L=function(a,b){this.l=a;this.Ec=b;this.a=a.a};c.L.prototype.t=q();c.B=function(a,b){this.type=a;this.l=a.l;this.c=b;this.a=a.a};c=c.B.prototype;c.t=q();c.za=q()})();
B.ff=function(){return[i,i,[[B.i.ab,e,m,m,m,m,m,m],[B.i.K,m,e,e,e,e,e,e],[B.i.Da,e,m,m,m,m,m,m],[B.i.hc,m,e,e,e,e,e,e]],[["t0",B.i.Da,i,i,[],m,[]],["t1",B.i.hc,["images/tiledbackground.png",4387060],i,[],m],["t2",B.i.K,i,[["Default",5,m,1,0,m,[["images/sprite2-default-000.png",184155,1,0.5,0.5,[],[]]]]],[],m],["t3",B.i.K,i,[["Default",5,m,1,0,m,[["images/sprite3-default-000.png",5172,1,0.501538,0.5,[],[-0.498462,-0.496622,0.427693,-0.496622,0.0769235,-0.427365,-0.16,-0.265203,-0.28923,-0.096284,-0.409231,
0.08277,-0.498462,0.467905]]]]],[["Solid",B.h.ia]],m],["t4",B.i.K,i,[["Default",5,m,1,0,m,[["images/sprite4-default-000.png",19646,1,0.500302,0.501608,[],[-0.466465,-0.501608,0.499698,-0.501608,0.499698,0.498392,0.469486,0.122186,0.396979,-0.189711,0.302115,-0.315113,0.18429,-0.324759,-0.1571,-0.0353697,-0.353474,-0.376206]]]]],[["Solid",B.h.ia]],m],["t5",B.i.K,i,[["Default",5,m,1,0,m,[["images/sprite5-default-000.png",29694,1,0.500891,0.500423,[],[-0.500891,-0.500423,-0.390374,-0.374472,-0.14082,
-0.279797,0.270945,-0.207101,0.497326,0.0633984,-0.0695183,0.229924,-0.381461,0.370245,-0.452763,0.499577]]]]],[["Solid",B.h.ia]],m],["t6",B.i.K,i,[["Default",5,m,1,0,m,[["images/sprite6-default-000.png",5941,1,0.501832,0.5,[],[-0.413919,-0.5,-0.366301,-0.241525,-0.135532,0.111582,0.21978,0.388418,0.498168,0.5,-0.501832,0.5]]]]],[["Solid",B.h.ia]],m],["t7",B.i.K,i,[["Default",5,m,1,0,m,[["images/sprite7-default-000.png",6687,1,0.500366,0.504065,[],[-0.401465,-0.504065,0.347986,-0.504065,0.432235,
0.235772,0.499634,0.422764,-0.495971,0.495935,-0.446154,0.089431]]]]],[["Solid",B.h.ia]],m],["t8",B.i.K,i,[["Default",5,m,1,0,m,[["images/sprite8-default-000.png",5762,1,0.5,0.501502,[],[0.149225,0.201201,0.5,-0.411411,0.5,0.498498,-0.5,0.456456,-0.172481,0.411412]]]]],[["Solid",B.h.ia]],m],["t9",B.i.K,i,[["Default",5,m,1,0,m,[["images/sprite9-default-000.png",33354,1,0.5,0.500522,[],[-0.145563,-0.125391,0.196429,-0.194357,0.411797,-0.326019,0.5,-0.500522,0.5,0.499478,0.426948,0.354231,0.253788,0.234065,
0.020022,0.160919,-0.409632,0.132707,-0.5,-0.109717]]]]],[["Solid",B.h.ia]],m],["t10",B.i.K,i,[["Default",5,m,1,0,m,[["images/sprite10-default-000.png",46153,1,0.5,0.500684,[],[-0.406918,-0.500684,-0.075472,-0.300958,0.321384,-0.411765,0.461006,-0.387141,0.5,-0.268126,0.474214,-0.071135,0.389308,0.035568,0.184906,0.114911,-0.055346,0.145007,-0.105031,0.25855,-0.083648,0.499316,-0.168553,0.499316,-0.237736,0.153215,-0.313208,0.02052,-0.486163,-0.150479,-0.5,-0.300958,-0.479245,-0.45554]]]]],[["Solid",
B.h.ia]],m],["t11",B.i.K,i,[["Default",5,m,1,0,m,[["images/sprite11-default-000.png",59265,1,0.5,0.5,[],[-0.182754,-0.5,-0.097169,-0.5,-0.00707799,-0.052632,0.239382,-0.01555,0.438224,0.07177,0.5,0.221292,0.467181,0.448565,0.286358,0.161483,0.151866,0.050239,0,0.016746,-0.174389,0.058612,-0.325611,0.204545,-0.446589,0.5,-0.5,0.334928,-0.404762,0.133971,-0.158301,-0.131579,-0.15444,-0.277512]]]]],[["Solid",B.h.ia]],m],["t12",B.i.K,i,[["Default",5,m,1,0,m,[["images/sprite12-default-000.png",7661,1,
0.5,0.5,[],[-0.287748,-0.293919,-0.00309399,-0.5,0.203589,-0.381757,0.367574,0,0.5,0.5,-0.5,0.5]]]]],[["Solid",B.h.ia]],m],["t13",B.i.K,i,[["Default",5,m,1,0,m,[["images/carsprite-default-000.png",6414,1,0.425,0.5,[],[-0.3625,-0.375,0.5,-0.35,0.575,0,0.5,0.35,-0.3625,0.375]]]]],[["BoundToLayout",B.h.bound],["ScrollTo",B.h.Jf],["Car",B.h.ve],["Pin",B.h.Yc]],m],["t14",B.i.hc,["images/tiledbackground2.png",949686],i,[],m],["t15",B.i.ab,i,i,[],m,[]]],[["Layout 1",2E3,2E3,m,"Event sheet 1",[["Layer 0",
0,e,"rgb(255, 255, 255)",m,1,1,1,m,[[[163,149,0,325,296,0,0,1,0.501538,0.5],3,[],[[]],[0,0,0,0]],[[1169,158,0,1655,311,0,0,1,0.500302,0.501608],4,[],[[]],[0,0,0,0]],[[282,1052,0,561,1183,0,0,1,0.500891,0.500423],5,[],[[]],[0,0,0,0]],[[137,1822,0,273,354,0,0,1,0.501832,0.5],6,[],[[]],[0,0,0,0]],[[1071,1938,0,1365,123,0,0,1,0.500366,0.504065],7,[],[[]],[0,0,0,0]],[[1869,1833,0,258,333,0,0,1,0.5,0.501502],8,[],[[]],[0,0,0,0]],[[1536,993,0,924,957,0,0,1,0.5,0.500522],9,[],[[]],[0,0,0,0]],[[1028,1672,
0,808,148,0,0,1,0.5,0.5],12,[],[[]],[0,0,0,0]],[[1021,1366,0,1554,836,0,0,1,0.5,0.5],11,[],[[]],[0,0,0,0]],[[1004,581,0,1590,731,0,0,1,0.5,0.500684],10,[],[[]],[0,0,0,0]]]],["Layer 1",1,e,"rgb(255, 255, 255)",e,1,1,1,m,[[[0,0,0,2E3,2E3,0,0,1,0,0],14,[],[],[0,0,0]],[[946,1488,0,80,40,0,0,1,0.425,0.5],13,[],[[1],[],[500,400,1E3,225,110,0.4,1,1],[]],[0,0,0,0]]]]],[]]],[["Event sheet 1",[[0,i,[[0,B.i.Da.prototype.o.Xc,i,m,m,m,m,[[9,37]]]],[]],[0,i,[[0,B.i.Da.prototype.o.Xc,i,m,m,m,m,[[9,39]]]],[]],[0,
i,[[0,B.i.Da.prototype.o.Xc,i,m,m,m,m,[[9,40]]]],[]],[0,i,[[-1,B.bc.prototype.o.Be,i,e,m,m,m]],[[15,B.i.ab.prototype.M.hg,i,[[2,"mattoglseby - 3"]]],[15,B.i.ab.prototype.M.Play,i,[[2,"mattoglseby - 3"],[1,[2,"music"]]]],[15,B.i.ab.prototype.M.jg,i,[[1,[2,"music"]],[3,0]]]]]]]],"media/",m,700,450]};window.cr=B;window.cr.createRuntime=B.vg;
